### ISSUE TITLE
MOAB 5

### ISSUE THREAD

**Issue by scopatz** [pyne/pyne#1004]
PyNE now seems to fail to compile or link against MOAB v5. cc @pshriwise @gonuke etc.

**Comment by gonuke** [comment]
Are you noting this as a change? As far as we know it never compiled/linked against MOAB v5.

There may be some quick hacks, but a key need that we are trying to work on is dropping PyTAPS for pyMOAB

**Comment by gonuke** [comment]
This is addressed (or was mostly addressed at the time) by #899 

I think that it may still be a race-condition issue of updating the pyne-deps docker image with MOAB v5 in order to show that this passes tests,... but we can't do that until we are sure that it passes tests.... and repeat...

**Comment by gonuke** [comment]
I recall now that #899 handles some changes in the interface for accessing `DAGMC` related stuff, but I'm not sure that there is, or ever will be, a version of PyTAPS that works with MOAB v5.

**Comment by scopatz** [comment]
Sorry for not being more clear.  There is now a conda-forge MOAB v5 package.  This breaks the pyne package because pyne was not pinned to use MOAB v4.  So in the short term it is probably a good idea to pin the pyne package to use moab 4, but in the long term I think we should ditch moab v4.

**Comment by gonuke** [comment]
This is closed in favor of #1250 that will address a variety of capabilities in conda-forge
