### ISSUE TITLE
Downloading Pyne

### ISSUE THREAD

**Issue by KennellyT** [pyne/pyne#1012]
Hey, This is Tyler Kennelly.

Currently I am trying to download pyne and I am having issues downloading pyne via conda.
I have tried:
conda install -c cyclus -c pyne pyne=VERSION
where version is 0.5.11 and it stated that,
"PackagesNotFoundError: The following packages are not available from current channels:

  - pyne=0.5.11

I attempted to install Pyne via the oracle virtualbox, but the pyne.ova file was going to take ~20 hours to download. 
Is there another way of downloading Pyne for windows 64?

Thank you

**Comment by scopatz** [comment]
Hi @KennellyT  are you using conda on windows?

**Comment by KennellyT** [comment]
Hi @scopatz 
I currently have  anaconda2 and anaconda3 on windows 64.

**Comment by scopatz** [comment]
Ahh yeah, that error message is correct, then.  PyNE does not currently support Windows.  Though #1001 is a pull request aims to add Windows support.  If you'd (or anyone else) would like to help out with that effort, that'd be great!

**Comment by KennellyT** [comment]
Ah, I see. Ok Ill take a look at #1001!
Thank you!

**Comment by gonuke** [comment]
@scopatz - I also noticed that @KennellyT was using the `cyclus` channel.  Is that preferred over the `conda_forge` channel?

**Comment by scopatz** [comment]
Ahh this is a fair point.  I don't think it would have changed the outcome, but in general yes. The cyclus channel doesn't really have anything in it anymore (in order to avoid confusion), but the pyne channel still has some MOAB /CGM / PyTAPS packages. 

We should be using the conda-forge channel from now on.

**Comment by ASamarkRoth** [comment]
Could you change the instructions in the readme: 

` conda install -c cyclus -c pyne pyne=VERSION`

to:

`conda install -c conda-forge -c pyne pyne=VERSION` ?

I could not manage otherwise (on Ubuntu 16.04).

**Comment by gonuke** [comment]
Closed by successful merge of new release into conda-forge
