### ISSUE TITLE
data.gamma_xrays runtime error

### ISSUE THREAD

**Issue by AGHVogt** [pyne/pyne#1020]
Hi, this is Andreas Vogt.
When calling 
In [8]: data.gamma_xrays(892270000)
I get the following runtime error: 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-4e8f7ba066c4> in <module>()
----> 1 data.gamma_xrays(892270000)
data.pyx in pyne.data.gamma_xrays()
RuntimeError: P��

Other nuclei work just fine, e.g.
In [8]: data.gamma_xrays(902320000)
Out[8]:
[(88.47, 0.002807402708729183),
 (85.43, 0.001718691938284006),
 (100.0, 0.001308041352986811),
 (12.3, 7.139185247404002)]

Is this a matter of the h5 table? I checked that data.gamma_xrays works at least for all even-mass nuclei along the 232Th and 238U decay chains.

Best regards!

**Comment by scopatz** [comment]
Hi @AGHVogt - yeah, I suppose that this nuclide is not in the data set.  Have you checked the h5 file to see if it is actually present?

**Comment by AGHVogt** [comment]
The nuclide has to be in the dataset since the following works:

In [5]: data.atomic_mass(892270000)
Out[5]: 227.027752283

In [7]: data.half_life(892270000)
Out[7]: 687072067.1999999

In [8]: data.decay_const(892270000)
Out[8]: 1.0088420322262598e-09

In [10]: data.decay_children(892270000)
Out[10]: set([872230000, 902270000])

In [11]: data.branch_ratio(892270000,902270000)
Out[11]: 0.9862000000000001

In [12]: data.decay_photon_branch_ratio(892270000,902270000)
Out[12]: (0.9999969379999999, nan)

In [13]: data.gamma_energy(892270000)
Out[13]:
[(9.3, 0.1),
 (12.9, 0.1),
 (15.2, 0.1),
....

In [14]: data.gamma_photon_intensity(892270000)
Out[14]:
[(0.00011, nan),
 (0.01, nan),
 (0.00063, nan),
....

Even the conversion intensities are there:
In [15]: data.gamma_conversion_intensity(892270000)
Out[15]:
[(326000.0, 19000.0),
 (51100.0, nan),
 (238.0, 6.0),
...

Only xray_gammas 
In [16]: data.gamma_xrays(892270000)
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-4e8f7ba066c4> in <module>()
----> 1 data.gamma_xrays(892270000)
data.pyx in pyne.data.gamma_xrays()
RuntimeError: 0�

produces the runtime error. I redownloaded and rebuilt the data with scripts/nuc_data_make. I evaluated all nuclei along the 232Th, 238U, and 235U decay chains. 227Ac is the only nucleus for which the xray data does not work. If at least an empty list would be returned...

Regards,
Andreas

**Comment by scopatz** [comment]
> The nuclide has to be in the dataset since the following works

Hi @AGHVogt, unfortunately just because a nuclide is in one part of the database doesn't mean that it is in another.  The point is well taken about not throwing an error, though, and returning an empty list. I can make this change.

**Comment by scopatz** [comment]
Oh weird this is a not-a-nucliude error when I try it.  This seems to be a legit error

**Comment by scopatz** [comment]
Ho-kay! a fix is now available in #1021
