### ISSUE TITLE
Broken PyNE data URL

### ISSUE THREAD

**Issue by moatazharb** [pyne/pyne#1030]
PyNE nuc_data_make fails to retrieve prebuilt data from http://data.pyne.io/

**Comment by scopatz** [comment]
Can you please provide a traceback? Thanks for reporting @moatazharb

**Comment by moatazharb** [comment]
![pyne_data](https://user-images.githubusercontent.com/5401832/39894531-c2ff5f74-546c-11e8-922d-414fe2528dc7.png)

**Comment by gonuke** [comment]
Should we move this data to the pyne/data repo?

**Comment by moatazharb** [comment]
It's working now. Thank you
