### ISSUE TITLE
use_fast_endftod import name issue

### ISSUE THREAD

**Issue by KennellyT** [pyne/pyne#1031]
I recently source installed Pyne for Linux. I was able to install--user but when I tried to build and install a database of nuclear data via:
scripts/nuc_data_make 
I received an issue: 
cannot import name 'use_fast_endftod'
After going through the source code online: http://fuelcycle.org/cyclus/api/namespacepyne.html#a314ad855be2083a69c8c807b137466ac

I was wondering what this name/function does and whether this issue has been seen before?

Thank you!
![use_f](https://user-images.githubusercontent.com/31637359/39944382-1a61edda-552c-11e8-88f6-5e548ab9079a.png)

![screenshot from 2018-05-11 14-52-07](https://user-images.githubusercontent.com/31637359/39944339-ee0acd38-552b-11e8-9bf8-06d7016a35a9.png)

**Comment by katyhuff** [comment]
I'm not sure of the solution or the cause by looking at this briefly, but I suspect more reading might reveal the solution. 

Slightly more information can be found through the pyne docs (you have linked the cyclus version of the pyne docs...)

See: http://pyne.io/devsguide/endf.html?highlight=endftod

and : https://github.com/pyne/pyne/blob/c0ba8ba30bc566811f6ee02251997063d795530c/pyne/_utils.pyx#L130

**Comment by KennellyT** [comment]
Thank you for the links. 
After looking at the second link (pyne/pyne/_utils.pyx), I think I now know where it the issue is coming from.
Thank you.

**Comment by katyhuff** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/f3b1c198-8c3a-4386-a2de-5902bf7309df-aef391d1-ee2a-4ffc-b1c7-1c24444a7cae-v1.png?transparent=1&palette=1&width=246)

**Comment by gonuke** [comment]
I think this is resolved.
