### ISSUE TITLE
rxname issue

### ISSUE THREAD

**Issue by KennellyT** [pyne/pyne#1033]
I was going through the nuclear data tutorial when I hit a bug with the rxname.child() function. 
When the 'a_br' variable is called:
a_br = data.branch_ratio(922290000,rxname.child(922290000,'a','decay'))
it outputs:
TypeError: expected bytes, str found (figure 1)

It seems that the issue is in the third input of rxname.child function ('decay'):
rxname.child(922290000,'a',**_'decay'_**) 

When left out it works fine and prints:
input: rxname.child(922290000,'a')
output: 902260000, (which is thorium 226) (figure 2)

I was wondering if this is an issue within the rxname.child function in rxname where the third variable is defined:
z ='n' (figure 3)

Thank you!
![a_br](https://user-images.githubusercontent.com/31637359/40269803-a1086d92-5b48-11e8-94ab-7d7536d8f843.png)
![rx_name_no_3rd](https://user-images.githubusercontent.com/31637359/40269812-c87a0a2a-5b48-11e8-9201-59bf8af854e0.png)
![rx_name_child](https://user-images.githubusercontent.com/31637359/40269813-cd9f203a-5b48-11e8-84da-e54187f681e7.png)

**Comment by scopatz** [comment]
Hi @KennellyT - thanks for pointing this out.  That function should be extended to also accept strings.  To get it running right now, you can use a bytes object for the third argument:

```python
rxname.child(922290000, 'a', b'decay')
```

**Comment by KennellyT** [comment]
Hey @scopatz - Thanks for the quick response! 
Your answer works and corrects the issue!
Thank you!

**Comment by scopatz** [comment]
Great! And a more permenant fix is in #1034

**Comment by KennellyT** [comment]
Nice!
Thank you
