### ISSUE TITLE
Tutorial print function in python 2

### ISSUE THREAD

**Issue by KennellyT** [pyne/pyne#1036]
Hey, 
I was going through the tutorials and I noticed that all the tutorials' print functions are written as:

print variable (python 2)
instead of: 

print(variable) (python 3)
I was wondering if the print functions should be updated to the python 3 way. I have been working through the tutorials and updating them so they are concurrent with python 3. Should I pull request these as an update(s)?

Thank you

**Comment by opotowsky** [comment]
#1271 closes this
