### ISSUE TITLE
Decay chain flow diagram idea

### ISSUE THREAD

**Issue by KennellyT** [pyne/pyne#1040]
Hey Pyne team,

I was going through the Pyne documentation and found the data.decay_data_children function. Recently I wrote up a basic code (figure 1) that allows the user to call a nucname.id and the amount of generations they want and the code will print out the decay chain for the nucname.id. 
I have not been able to find the probability of a certain decay type for isotopes that decay in many forms in Pyne's documentation so if this is not in Pyne would there be any interest in a pull request for this function/data set? I was wondering if there is any interest in incorporating this decay chain feature (including probability) into Pyne?
Thank you.
![decay_chain](https://user-images.githubusercontent.com/31637359/40491661-4270cb0e-5f34-11e8-83e1-47a1ab9bd3b7.png)

**Comment by scopatz** [comment]
Hi @KennellyT - we'd love to have a function link that!  Please put in a PR

Note that we also have a function which will plot the decay chain for a nuclide.  It is the `graph()` function in the `pyne.gui.decaychain` module.

**Comment by KennellyT** [comment]
Hi @scopatz 
I just used the pyne.gui.decaychain graph and it looks great! I will continue my work on the decay chain information function but incorporate it with pyne.gui.decaychain.
Thank you!

**Comment by scopatz** [comment]
Great thanks!
