### ISSUE TITLE
cache.py, channels.py, sigma_s() issues

### ISSUE THREAD

**Issue by KennellyT** [pyne/pyne#1043]
Hey,
I was working with XSCache and channels and I noticed a reoccurring issue with sigma_s. When called as:
`sigma_s(10010000)`
an error pops up as:
![image](https://user-images.githubusercontent.com/31637359/40790554-e51e561a-64ba-11e8-83fd-71d488782edb.png)
The bug seems to propogating from channels.py:
```
 # Get some needed data
    E_g = xs_cache['E_g']
    **G = len(E_g) - 1**
    b = data.b(nuc)
    aw = data.atomic_mass(nuc)
```
where E_g is a none type.

**Comment by scopatz** [comment]
Hi @KennellyT, thanks for reporting! I think that this means that you have to set the `dst_group_struture` or the `E_g` in the cache

**Comment by KennellyT** [comment]
Hi @scopatz,
Thank you, that should work as I did not set the structure in the cache. I think this is more of a chain-fail  due to my issue with cache, #1037. Thank you, I'll close this issue.

**Comment by scopatz** [comment]
Happy to help!
