### ISSUE TITLE
gammaspec.py

### ISSUE THREAD

**Issue by KennellyT** [pyne/pyne#1044]
Hey,
I was going through gammaspec.py and creating a tutorial for its usage and I ran into some issues. 
When I ran:`
gammaspec.read_spe_file('/home/tyler/Documents/Cs-137_1min(1).spe')`
This error occurred:
 ```
File "/home/tyler/anaconda3/lib/python3.6/site-packages/pyne/gammaspec.py", line 151, in read_spe_file
    raise RuntimeError('Spe file format is not supported by this function')

RuntimeError: Spe file format is not supported by this function
```
I am confused as to why the .spe file format is not supported as this functions asks for the file path to a .spe file. I saw that in the documentation it states:

> checks version of .spe file matches currently supported version
Does this function only support certain .spe files? If so, can I change gammaspec.py so that it will accept more .spe files? 
Thank you

**Comment by scopatz** [comment]
Hi @KennellyT - this module defintiely needs some love and attention. Any help would be greatly appreciated.

**Comment by KennellyT** [comment]
Hey @scopatz- Sounds great, I am currently editing gammaspec.py to allow more types of .spe files to be read and analyzed.
I have a Gaussian distribution python code that I made for a prior laboratory class that I may implement/compare to gammaspec.py down the road.
Thank you

**Comment by scopatz** [comment]
That'd be awesome! Thanks!

**Comment by KennellyT** [comment]
Quick question @scopatz , if the .spe does not have certain information such as:
Spectrum name, Detector ID, Detector description, nor Energy fit should I have gammaspec.py default those values to "N/A"?

**Comment by scopatz** [comment]
Probably should give them as Python `None`

**Comment by KennellyT** [comment]
@scopatz 
Thank you! 
I got gammaspec.py to accept and read .spe files that begin with '$SPEC_ID:'.
I should have gammaspec.py updated and pull requested by Monday afternoon.

**Comment by scopatz** [comment]
Sweet, looking forward to it!

**Comment by KennellyT** [comment]
Quick question:
I got gammaspec.py to accept and read the parameters of .spe files that begin with '$SPEC_ID:'.
I was looking at issue Spectroscopy Module #43, where some of the other functions of this package would be:
peak search
compare 2 spectra
background subtract
peak fitting
peak area calculation
track peak over time using multiple spectra files
I was wondering if pyne already has modules for these tasks? If not I can develop them as I am currently developing a peak search function and calibration function via the package peakulits and using the pyne data on gamma energies.

**Comment by scopatz** [comment]
I think our spectroscopy capabilities in general are under-developed. It would be great to have more work in this direction

**Comment by KennellyT** [comment]
I have partially developed a FWHM function. 
Back to gammaspec.py, has the GammaSpectrum class been known to cause problems. 
For example after running:
```
import gammaspec as gs
spec_file_path = 'cs-137.spe'
spectrum = gs.GammaSpectrum()
spectrum.file_name = spec_file_path
gs.read_SPEC_ID_file(spec_file_path='cs-137.spe')
print(gs.read_SPEC_ID_file(spec_file_path='cs-137.spe'))
```
gs.read_SPEC_ID_file(spec_file_path='cs-137.spe') does not know what spectrum is while after printing (gs.read_SPEC_ID_file(spec_file_path='cs-137.spe')), the entirety of spectrum is printed as seen in figure 1 below.
![image](https://user-images.githubusercontent.com/31637359/40892451-f717a02a-675c-11e8-805e-09878729c2d1.png)
The form of this print out is coming from the GammaSpectrum class in gammaspec.py 
```
class GammaSpectrum(spectanalysis.PhSpectrum):
    """GammaSpec class includes gamma specific variables"""

    def __init__(self, real_time=0, live_time=0, det_id='',
                 det_descp='', start_date='', start_time='',
                 calib_e_fit=None, calib_fwhm_fit=None, eres=0, file_name=''):
        """Define gamma spectrum specific variables """
        super(GammaSpectrum, self).__init__()
        self.real_time = real_time
        self.live_time = live_time
        self.dead_time = real_time - live_time
        self.det_id = det_id
        self.det_descp = det_descp
        self.start_date = start_date
        self.start_time = start_time
        self.calib_e_fit = [] if calib_e_fit is None else calib_e_fit
        self.calib_fwhm_fit = [] if calib_fwhm_fit is None else calib_fwhm_fit
        self.eres = eres
        self.file_name = file_name

    def calc_ebins(self):
        """Calculate the energy value for each channel."""
        channels = self.channels = np.asarray(self.channels, float)
        self.ebin = self.calib_e_fit[0] + (self.calib_e_fit[1] * channels) + \
                    (self.calib_e_fit[2] * channels ** 2)

    def __str__(self):
        """Print debug information"""
        print_string = ('Debug print of all header variables\n'
                        'The real time is: {x.real_time}\n'
                        'The live time is: {x.live_time}\n'
                        'The dead time is: {x.dead_time}\n'
                        'Detector ID: {x.det_id}\n'
                        'Detector description: {x.det_descp}\n'
                        'Start date: {x.start_date}\n'
                        'Start time: {x.start_time}\n'
                        'Start channel number: {x.start_chan_num}\n'
                        'Number of channels: {x.num_channels}\n'
                        'Energy calibration fit: {x.calib_e_fit}\n'
                        'FWHM calibration fit: {x.calib_fwhm_fit}\n'
                        'Spectrum: {x.counts}\n'
                        'File name: {x.file_name}').format(x=self)
        return print_string
```
Am I calling/using GammaSpectrum() incorrectly ?
Thank you

**Comment by scopatz** [comment]
>  has the GammaSpectrum class been known to cause problems

I don't think many people use this functionality, so it is probably safe to say that there are bugs

**Comment by KennellyT** [comment]
Thank you.
I am closing this issue as gammaspec.py has been updated to accept other types of .spe files. I will open other issue(s) for GammaSpectrum and other functions for gamma spectrometry.
