### ISSUE TITLE
Gamma spectrometry (compton edge, backscatter, single/double escape)

### ISSUE THREAD

**Issue by KennellyT** [pyne/pyne#1047]
Hey, 
I was wondering if pyne already has a calculator that calculates the Compton edge, backscatter, single/double escape energies given an input gamma energy? I have developed a code for these functions (see below) and I am just checking that these function have not already been implemented into pyne.
Also, if this function was to be implemented should I create a test for this function in `tests`?
Code sample: 
![image](https://user-images.githubusercontent.com/31637359/40930145-7378e78e-67ec-11e8-94c3-b1ab4178af8c.png)

**Comment by scopatz** [comment]
Hi @KennellyT - yeah, I doubt that these functions have been implements, so any implementations would be most welcome! And yes, tests are needed with all code additions.

**Comment by KennellyT** [comment]
@scopatz, 
I have the base code written and I will write the tests for this code and push them tomorrow.

**Comment by scopatz** [comment]
Sounds great!
