### ISSUE TITLE
Does Pyne have a library on X-Ray Mass Coefficients ?

### ISSUE THREAD

**Issue by KennellyT** [pyne/pyne#1048]
I was recently developing a function to calculate the intensity of a beam through a slab of thckness T. While creating this function, I noted that I needed the mass attenuation coefficient of the material to calculate the intensity. 
I was wondering if pyne has this library? If not, I can write a webscrapper to parse through data sets such as: https://physics.nist.gov/PhysRefData/XrayMassCoef/ComTab/water.html and gather the data so that it could be used more efficiently for the user.

**Comment by katyhuff** [comment]
The mass attenuation coefficient has a relationship to the cross section (\sigma_{tot}). I believe we have the total photon cross sections in pyne somewhere...

![image](https://user-images.githubusercontent.com/393899/40992259-50312cae-68c4-11e8-986c-561bd8443b69.png)

**Comment by KennellyT** [comment]
I found that the photon cross section data is in the pyne.data module, pyne.xs.channels.sigma_t, and ENDF Reader. I can use these to implement this function. 
Thank you @katyhuff!

**Comment by katyhuff** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/1b492f65-6292-40d6-956e-e1c962b347f4-aef391d1-ee2a-4ffc-b1c7-1c24444a7cae-v1.png?transparent=1&palette=1&width=246)
