### ISSUE TITLE
Atomic mass update

### ISSUE THREAD

**Issue by KennellyT** [pyne/pyne#1057]
A new '[ATOMIC MASS ADJUSTMENT](http://amdc.impcas.ac.cn/masstables/Ame2016/mass16.txt)' file was released in Mar 2017 by the same source that released the current atomic mass data pyne uses. Pyne's current atomic mass data file ([mass.mas12](https://github.com/pyne/pyne/blob/develop/pyne/dbgen/mass.mas12)) was created in Nov 2012. The atomic mass data in the 2012 file differs from the 2017 file.

**Comment by katyhuff** [comment]
@KennellyT if you haven't started this, maybe @makoziol0 can give it a try?

**Comment by KennellyT** [comment]
@katyhuff, that sounds great!

**Comment by makoziol0** [comment]
Any reason to keep the old mas12 file? @katyhuff

**Comment by katyhuff** [comment]
Hm. This is a good question. I suppose we should move forward in time, rather than preserving the past. 

But, we should check in with folks who might be impacted. @paulromano @pshriwise ... thoughts?

**Comment by paulromano** [comment]
We're also using the 2012 data in OpenMC. I can't think if of a compelling reason to stick with the older data though.

**Comment by katyhuff** [comment]
Makes sense. go ahead, @makoziol0

**Comment by gonuke** [comment]
closed by #1281
