### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by jincairen** [pyne/pyne#1062]
sorry for asking repeatedly

**Comment by zxkjack123** [comment]
Let's discuss this problem at https://github.com/pyne/pyne/issues/1063.

**Comment by jincairen** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
OK,thank you for your reply.Hope it can be solved soon.



                


    On 9/29/2018 00:13，Xiaokang Zhang<notifications@github.com> wrote： 


Let's discuss this problem at #1063.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    
        font{
            line-height: 1.6;
        }
    
        font{
            line-height: 1.6;
        }
