### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by jincairen** [pyne/pyne#1063]
after running"scripts/nuc_data_make",report an error:"urllib.error.HTTPError: HTTP Error 404: Not Found"
how to solve this problem?
thank you !!

**Comment by zxkjack123** [comment]
This problem happens because of this line:
https://github.com/pyne/pyne/blob/cc70bcd553e2cfd150e5708cb58b628eccf1eea8/pyne/dbgen/nuc_data_make.py#L67

@scopatz The url `http://data.pyne.io/prebuilt_nuc_data.h5` is no longer exist. I didn't find this file in `pyne/data`. Was the process of building `nuc_data` changed? Or just the `prebuild_nuc_data.h5` moved to another place?

**Comment by gonuke** [comment]
@scopatz if we can get the data from that server, we can move it to the `data` repo here

**Comment by pshriwise** [comment]
Adding a link to a related PR in `pyne/data` [here](https://github.com/pyne/data/pull/13)

**Comment by pshriwise** [comment]
I think I managed to grab a working `nuc_data.h5` file by running `nuc_data_make` inside one of the CI Docker containers. Can this be served in the same way as `prebuilt_nuc_data`?

**Comment by pshriwise** [comment]
Found the `origin-benchmark-hdf5` dataset in that docker image as well.

**Comment by gonuke** [comment]
Yes - it should be possible to serve any/all of these from pyne/data

**Comment by jincairen** [comment]
I have tried to install PyNE again.
Unfortunately,it has reported the same error as before.
I've tried two different methods: 
using command"./ubuntu_16.04.sh stable" to install it from scratch 
or
using source install by updating two folders:pyne and tests(I found only these two folders have been revised recently).
So,can anyone tell me if it's my fault or if that error hasn't been fixed yet?
thank you very much.

**Comment by pshriwise** [comment]
Can you try `./ubuntu_16.04.sh` without `stable`? The stable version won't have these fixes sadly.

**Comment by jincairen** [comment]
Thank you for your reply.
Using ./ubuntu_16.04.sh ,I get this:

Extracting PyTAPS-1.4-py2.7-linux-x86_64.egg to /root/.local/lib/python2.7/site-packages
PyTAPS 1.4 is already the active version in easy-install.pth
Installing tagviewer script to /root/.local/bin

Installed /root/.local/lib/python2.7/site-packages/PyTAPS-1.4-py2.7-linux-x86_64.egg
Processing dependencies for PyTAPS==1.4
Searching for numpy==1.11.0
Best match: numpy 1.11.0
numpy 1.11.0 is already the active version in easy-install.pth

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for PyTAPS==1.4
ubuntu_mint.sh: 行 114: $1: 未绑定的变量

"未绑定的变量"means "Unbound variable".
So?

**Comment by pshriwise** [comment]
Apologies. You’ll want to try ‘./ubuntu_16.04.sh dev’

The install script requires either a ‘stable’ or ‘dev’ argument.

**Comment by jincairen** [comment]
It works!
Thank you very much!

**Comment by pshriwise** [comment]
Glad to help :) Thanks for bringing this to our attention. 

This issue has been resolved by #1065
