### ISSUE TITLE
Python name for configparser

### ISSUE THREAD

**Issue by shimwell** [pyne/pyne#1079]
"import ConfigParser" statement in r2s.py might need changing as it causes errors in python3

I believe the name has changed to "import configparser"

**Comment by zxkjack123** [comment]
Unfortunately, as far as I know, we can't use python3 for PyNE R2S. Because the current PyNE R2S relies on a mesh related module which is compatible for only python2 So, if you are going to use PyNE R2S workflow, you have to swith to python2.

**Comment by zxkjack123** [comment]
This problem should be solved as PR #1132 get merged. @Shimwell Could you please update PyNE and try it again?

**Comment by zxkjack123** [comment]
Close it, as it should have been solved in PR#1132.
