### ISSUE TITLE
FileNotFound returning invalid char pointer

### ISSUE THREAD

**Issue by pshriwise** [pyne/pyne#1105]
The `FileNotFound` error message is returned via `const char*` which is created by a string that goes out of scope in its error message function `what()`. When that string goes out of scope, the pointer is no longer valid and has been reported to cause garbled text by @zxkjack123. This string should be kept in memory by adding an attribute to the class so that string exists for the lifetime of the exception object.

**Comment by zxkjack123** [comment]
Well this error is actually found by @ljacobson64 in #1099 , here:
https://github.com/pyne/pyne/pull/1099#issuecomment-466673262

**Comment by zxkjack123** [comment]
There isn't a `FileNotFound` error in python [build-in exceptions](https://docs.python.org/2/library/exceptions.html#module-exceptions), but I find that there is an [IOError](https://docs.python.org/2/library/exceptions.html#exceptions.IOError).

Throw an `IOError` is at least a better way than throw a `runtime_error` when the `file not found` happens.

**Comment by pshriwise** [comment]
This has been addressed in #1107. Thanks @gonuke!
