### ISSUE TITLE
pass back list of cells from particle_birth

### ISSUE THREAD

**Issue by gonuke** [pyne/pyne#1109]
The standard usage of the source sampling routines requires a search for the source cell after determining the x,y,z location.  This is currently a linear search over all the cells in a problem.

However, we already know which source voxel this is, and therefore we know what possible cells could exist at this point, typically many fewer than the number of cells in a problem.  If the particle birth method passed back the list of possible cells, we could narrow the linear search to that set of cells.

``` fortran
! only allocate this on the first particle
if (nps == 1)
    call get_max_num_cells(max_num_cells)
    allocate(max_num_cells) cell_list
end if
call particle_birth(rands, xxx, yyy, zzz, erg, wgt, cell_list)
icl_tmp = find_cell(cell_list)
```

**Comment by gonuke** [comment]
This can be done as part of `sampling_setup`

**Comment by zxkjack123** [comment]
Close it as the #1118 get merged.
