### ISSUE TITLE
allow user to turn off void rejection in source sampling routine

### ISSUE THREAD

**Issue by gonuke** [pyne/pyne#1111]
In the source sampling routine included for MCNP, the second value on the `idum` card indicates how many times to reject a sample because it has been born in the void.  This is based on the origin of this sampling capability - sampling a photon source from activated material. 

However, if one wants to use those same routines to sample a mesh for other purposes - e.g. a neutron source in the "vacuum" of a plasma chamber, then it is not appropriate to reject the voids.

One simple solution is to use the second `idum` entry; if it's value is < 0 then void rejection is turned off.

**Comment by zxkjack123** [comment]
Close it, as it has been resolved in PR #1158.
