### ISSUE TITLE
Material.decay_heat() Memory Error

### ISSUE THREAD

**Issue by makoziol0** [pyne/pyne#1120]
Material decay heat seems to be broken. It hasnt worked for any material I have tested.

Code:
```
from pyne.material import Material
test = Material({922350000: 1})
print(test.decay_heat())
```

Error:
```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-36-423a8d557ac3> in <module>
      1 test = Material({922350000: 1})
----> 2 test.decay_heat()

material.pyx in pyne.material._Material.decay_heat()

MemoryError: std::bad_array_new_length
```

**Comment by gwenchee** [comment]
What version of pyne are you using?

**Comment by aruzzo** [comment]
@makoziol0 I was able to reproduce this error by having the nuc_data.h5 file open with vitables at the same time as trying to compute test.decay_heat(). Closing the nuc_data file fixed the error and test.decay_heat() ran normally.

**Comment by gonuke** [comment]
closing as not reproducible
