### ISSUE TITLE
pyne.io Virtual Box link does not work

### ISSUE THREAD

**Issue by aruzzo** [pyne/pyne#1135]
On the pyne.io page for VirtualBox: [http://pyne.io/install/vb.html#vb](url), the link for installing the PyNE ova file doesn't work: [http://data.pyne.io/pyne-0.5+yt.ova](url). It states that the resource could not be found.

**Comment by bam241** [comment]
@aruzzo a vb box can be found here : https://uwmadison.box.com/shared/static/1kvzvh3js0enwa1j8u9dx6bdc5e4xzxn.ova

we need to update the link on the website.
sorry about that !

**Comment by aruzzo** [comment]
Thanks for the help!
