### ISSUE TITLE
source.F90 should use "implicit none"

### ISSUE THREAD

**Issue by ljacobson64** [pyne/pyne#1138]
source.F90 currently uses `implicit real`, which automatically assigns the `real` type to variables based on the first letter of the variable name. This is not good modern code practice, and can lead to a lot of issues.

For example, recently DAGMC was updated to have the newer source sampling routines present in pyne, in which some function signatures changed, but the source.F90 was not updated. The compiler was perfectly happy to compile DAGMC despite the incompatibility between the source sampling routines and source.F90. The error was not noticed until trying to run a problem using the source sampling routines, at which point a runtime error occurred.

`implicit none` means that the type of every variable must be declared explicitly. If `implicit none` were used, the aforementioned problem with DAGMC would have triggered a compiler error, and it would have been fixed before being merged into DAGMC.

I will submit a PR that fixes this soon.

**Comment by gonuke** [comment]
Fixed in #1139
