### ISSUE TITLE
CI-docker python package

### ISSUE THREAD

**Issue by bam241** [pyne/pyne#1144]
Maybe we should install all the python dependencies with `pip` as suggested in pyne/install_scripts#32 
As we can see [[see](https://github.com/pyne/pyne/blob/develop/docker/ubuntu_18.04-dev.dockerfile)], 10 python package are installed with `pip`:
- `sphinx`
- `cloud_sptheme`
- `prettytable`
- `sphinxcontrib_bibtex`
- `numpydoc`
- `nbconvert`
- `numpy`
- `nose`
- `cython`
- `future`

and 4+1 are still installed with `apt-get`:
- `nose` (yes installed with `apt-get` then overwritten by `pip`)
- `matplotlib`
- `tables`
- `scipy`
- `jinja2`

**Comment by gonuke** [comment]
closed by #1263
