### ISSUE TITLE
Outdated Documentation for Supported Platforms

### ISSUE THREAD

**Issue by nathanb01** [pyne/pyne#1148]
The file [`supported.rst`](https://github.com/pyne/pyne/blob/develop/docs/install/supported.rst) could use some updating. Since all of the listed OS's have reached end of life, I doubt we still build and test PyNE on these platforms. I'm not sure where to find a complete list of the builds that we test but I found a short [list](https://github.com/pyne/pyne/blob/develop/.circleci/config.yml) in `.circleci` containing python2 with/without PyMOAB/DAGMC and python3 without PyMOAB and DAGMC, all built on ubuntu 18.04.

Additionally, the information on the binaries seems to be outdated as well. Viewing the conda [site](https://anaconda.org/conda-forge/pyne/files) suggests that we have binaries for Mac and Linux with releases 5.11, 5.10, 5.3, and 5.1.

**Comment by nathanb01** [comment]
Recommended: Documentation label

**Comment by nathanb01** [comment]
I have made an attempt at updating this documentation page but I am unsure of a few things.

1. I don't think I have a complete list of the OS versions we test on.
2. Should I list all of the latest releases or just the most recent one.
3. Which version of python3 does circleci run and should that be the only python3 version listed.

My first draft can be found [here](https://gist.github.com/nathanb01/f02b705dc2ea19eece86f503c94f2f38) and the original can be found [here](https://github.com/pyne/pyne/blob/develop/docs/install/supported.rst).

**Comment by gonuke** [comment]
Be sure to pull the contribution from @nathanb01  if it's still useful

**Comment by opotowsky** [comment]
I believe #1285 closes this Issue.
