### ISSUE TITLE
CI tests don't incorporate new atomic mass data 

### ISSUE THREAD

**Issue by aruzzo** [pyne/pyne#1151]
As previously stated by @katyhuff ([original comment here](https://github.com/pyne/pyne/pull/1092#issuecomment-507408395)), the CI tests aren't incorporating the new atomic mass data from PR #1092 and are instead using old data in the docker image. Some potential fixes could be running nuc_data_make or perhaps doing so only if a particular PR flag is present.

**Comment by aruzzo** [comment]
In the CircleCI config.yml file, I added [--clean 2 and fetch-prebuilt False](https://github.com/aruzzo/pyne/blob/3b0d46dec1b51ad4dfe9f893f6537d98fcc4fab5/.circleci/config.yml#L77) to have the docker build the nuc_data file from scratch. When doing this, I encountered two data building issues:

1. During the py3_build [[CircleCI test here](https://circleci.com/gh/aruzzo/pyne/45)], attempting to download the neutron summary zip file KAERI from [http://data.pyne.io/kaeri.zip](http://data.pyne.io/kaeri.zip) resulted in an HTTP Error 404: not found. 
I thought that the KAERI link was dead as the data.pyne.io server no longer exists, but somehow the py2_build seems to be able to download the kaeri.zip file and read the data from it.

2. During the py2_build [[CircleCI test here](https://circleci.com/gh/aruzzo/pyne/44)], attempting to grab the NDS fission product yield data from [https://www-nds.iaea.org/sgnucdat/c3.htm](https://www-nds.iaea.org/sgnucdat/c3.htm) resulted in an HTTP error 403: forbidden. I tested opening the url [[test here](https://gist.github.com/aruzzo/929dd54d462a3555596574d9142463c5)] and urllib2 is unable to access the website: `The owner of this website (www-nds.iaea.org) has banned your access based on your browser's signature (4f1c3ec779b255f8-ua48)`.

**Comment by aruzzo** [comment]
A little update; I'm able to have CircleCI load in the new atomic mass file by adding `-m atomic_mass` to the config.yml file along with a few other changes. To have pyne actually build the new atomic mass data, the `make_atomic_mass` function in dbgen/atomic_mass.py was changed to `pass` instead of `return` if the atomic_mass node already exists and then delete the prebuilt atomic mass node in the nuc_data.h5 file with `kdb.remove_node('/atomic_mass')` in dbgen/atomic_mass.py. These changes can be seen ([here](https://github.com/aruzzo/pyne/compare/e725758..2e864e9)). 

There are still discrepancies with some test values, though. In one of the CircleCI tests with the new atomic mass data seen ([here](https://circleci.com/gh/aruzzo/pyne/74)), the `test_gamma_child_byen` in test_data.py fails (this test also fails with the old atomic mass data).
I then changed the data in `test_gamma_child_byen` to what it was previously so other tests could run. The next test failure was `test_dose_per_g` in test_material.py seen ([here](https://circleci.com/gh/aruzzo/pyne/90)). Looking back at the original PR ([here](https://github.com/pyne/pyne/pull/1092/files)), it seems like this test wasn't updated.

**Comment by aruzzo** [comment]
In total, I've found 5 test files that still contain failures:

1. test_data.py: `test_gamma_child_byen` has a different ordered list that doesn't match. The list was changed in a commit back in the original PR but it seemed to break this test [(change seen here)](https://github.com/pyne/pyne/commit/ade9057fec63e82ec307555747a5208fa26628b9#diff-f3725fbba011ae33a08160d9a35a7763)

`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/root/repo/tests/test_data.py", line 283, in test_gamma_child_byen
    1002560000])
AssertionError: Lists differ: [391020000, 521320000, 7317200... != [391020000, 521320000, 7317200...
First differing element 9:
801910000
370780000
  [391020000,
   521320000,
   731720000,
   791870000,
   791870000,
   832120000,
   832120000,
   922380000,
   982500000,
   801910000,
   370780000,
   691520000,
   771860000,
   801910000,
   882210000,
   922380000,
   521320000,
   521320000,
   521320000,
   681700000,
   741800000,
   741800000,
   591330000,
   591330000,
   741800000,
   792000000,
   872210000,
   611560000,
   1002560000]`

2. test_material.py: `test_dose_per_g` the assertion value hasn't been updated

`Traceback (most recent call last):
  File "/root/repo/tests/test_material.py", line 247, in test_dose_per_g
    assert_almost_equal(obs2[key], exp2[key])
AssertionError: 27.11394777435299 != 27.1139475504 within 7 places`

3. test_mcnp.py: `test_read_mcnp` was updated to be `assert_almost_equal` instead of `assert equal` in the original PR but this also removed the `.keys()` from the lists [(change seen here)](https://github.com/pyne/pyne/commit/5a8a925849f5ca6431ed02b726a69224b2e8fd72#diff-382e65542ea458e5bc5fa0fc06a5c917)

`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/root/repo/tests/test_mcnp.py", line 551, in test_read_mcnp
    list(read_materials[2]._mats.keys())[0].comp)
  File "/usr/lib/python2.7/unittest/case.py", line 555, in assertAlmostEqual
    if round(abs(second-first), places) == 0:
TypeError: unsupported operand type(s) for -: 'MapIntDouble' and 'MapIntDouble'`

4. test_partisn.py: `test_get_material_lib_with_names` and `test_get_material_lib_no_names` the assertion values haven't been updated

`Traceback (most recent call last):
  File "/home/pyne-test/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pyne-test/Desktop/pyne/tests/test_partisn.py", line 45, in test_get_material_lib_with_names
    assert(mat_lib == mat_lib_expected)
AssertionError`
`Traceback (most recent call last):
  File "/home/pyne-test/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pyne-test/Desktop/pyne/tests/test_partisn.py", line 72, in test_get_material_lib_no_names
    assert(mat_lib == mat_lib_expected)
AssertionError`

5. test_chainsolve.py: `test_tm171_decay` has a slightly different assertion value. This seems to be a discrepancy between the number of significant figures (the Material returns a value to 16 decimal places while transmute returns a value to 17 decimal places). Maybe `assert_almost_equal` would be better?

`Traceback (most recent call last):
  File "/home/pyne-test/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pyne-test/Desktop/pyne/tests/transmute/test_chainsolve.py", line 136, in test_tm171_decay
    assert_equal(exp, obs['TM171'])
AssertionError: 0.2499747878457496 != 0.24997478784574964`

**Comment by aruzzo** [comment]
@katyhuff @makeclean @gonuke @pshriwise @zxkjack123 I'd like to check if this is the best way to incorporate the new mass data into pyne. Currently, CircleCI fetches the prebuilt_nuc_data file by default. Since `--fetch-prebuilt false` has some issues with dead links and forbidden access, I modified atomic_mass.py and materials_library.py in pyne/dbgen to edit the nuc_data.h5 file. They delete the outdated mass and materials library nodes in nuc_data.h5 and then write in the new data. I added `-m atomic_mass,materials` to the nuc_data_make call in config.yml so CircleCI would incorporate the new data. Is this the best way to update CI or is there some other preferred method?

**Comment by pshriwise** [comment]
I'll propose that we update the `prebuilt_nuc_data.h5` file in the `pyne/data` repo rather than modifying it after the download. It might be a little tricky to keep that file and the `pyne/pyne` repo version in sync, but hopefully we won't have to do this too often.

**Comment by zxkjack123** [comment]
It seems that many atomic data are manually changed. In the test functions, some nuc data from `h5` file and manually defined value are compared. Well, these data are actually from a `mass.mas16`. I have a suggestion:
- Add some functions to read specific data from `mass.mas16` (also functions to test the data reading)
- Compare the data from `h5` and `mass.mas16` in the test functions

By this change, it will be much easier if we need to update to another atomic mass data in the future.

**Comment by gonuke** [comment]
New data was merged on github.com/pyne/data and its use in CI was confirmed after #1281
