### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by bam241** [pyne/pyne#1161]
As we maintain docker image/container for the CI, we should also push a `pyne/pyne:latest` and a `pyne/pyne:stable` on develop merge and tags respectively

**Comment by zxkjack123** [comment]
There should be a PR merge event triggered code to update these docker images automatically.

**Comment by gonuke** [comment]
Have special dockerfiles in repo that are targets for autobuild on dockerhub.  Then every time there is a merge in dev, it will autobuild.

**Comment by gonuke** [comment]
This has been superseded by various improvements in CI and docker support.
