### ISSUE TITLE
Half life time should be nan if nuclide isn't found in database

### ISSUE THREAD

**Issue by phll** [pyne/pyne#1164]
When you try to retrieve the half life time of an unknown isotope 'inf' is returned. For example
`nucdat.half_life("Cm-253")` produces the output 'inf', while this isotope cannot be found in the nudat2 data https://www.nndc.bnl.gov/nudat2/chartNuc.jsp . 
Wouldn't it make more sense if pyne would return 'nan' in such cases, like it does for known isotopes with unknown half life time (e.g. U-241)?

**Comment by ZoeRichter** [comment]
So right now, the current behavior is to assume any nuclide not found is stable (an infinite half-life).  Is it worthwhile to create a list of known stable isotopes to check against to determine if it returns inf or nan?
