### ISSUE TITLE
NNDC ENDF link not available

### ISSUE THREAD

**Issue by zxkjack123** [pyne/pyne#1174]
Several nuclear library data will be downloaded during the unit test. However, the ENDF of NNDC is currently not available, for example this link: http://www.nndc.bnl.gov/endf/b6.8/tapes/tape.100, used by `test_endf.py` is now not available.

Actually, the `http://www.nndc.bnl.gov/endf` is not available now:
```
Not Found
The requested URL /endf/ was not found on this server.
```

Where can we find a replacement for it?

**Comment by gonuke** [comment]
That seems like an error - I wonder if we should report it.

**Comment by zxkjack123** [comment]
Close this PR because the link is available again.
