### ISSUE TITLE
What happened to Fe-54

### ISSUE THREAD

**Issue by petersondroogh** [pyne/pyne#1177]
Ran a script and it looks like Fe-54 disappeared for a compound.  See below and see jupyter notebook
 
Josh
 
 
 
 
 
Fe = Material({"Fe": 1})

print(Fe)
print(Fe.expand_elements())
Material:
mass = 1.0
density = -1.0
atoms per molecule = -1.0

Fe     1.0
Material:
mass = 1.0
density = -1.0
atoms per molecule = -1.0

**Fe54   0.056455582260770826**
Fe56   0.9190152877284079
Fe57   0.021603686168514644
Fe58   0.0029254438423065078
[13]:
SST_17_7 = Material({'C': 0.09,'Al': 1.125, 'Si': 1, "P":0.05, "S":0.03, "Cr": 17, "Mn": 1, "Fe": 72.455, "Ni": 7.25})
print(SST_17_7)
print(SST_17_7.expand_elements())
​
Material:
mass = 100.0
density = -1.0
atoms per molecule = -1.0

C      0.0009
Al     0.01125
Si     0.01
P      0.0005
S      0.0003
Cr     0.17
Mn     0.01
Fe     0.72455
Ni     0.0725
Material:
mass = 100.0
density = -1.0
atoms per molecule = -1.0

C12    0.0009472378926112231
C13    1.1101687524012774e-05
Al27   0.01197924475169045
Si29   0.0005146953184818976
Si30   0.0003513788632771117
S33    2.463594541253385e-06
S34    1.4382255910940597e-05
S36    3.5832325541300614e-08
Cr50   0.007555194668707555
Cr52   0.1515123334844287
Cr53   0.017511097804137166
Cr54   0.004441072512715638
**Fe56   0.709035552982112**
Fe57   0.016667602567098507
Fe58   0.00225702849576633
Ni58   0.051876424187422235
Ni60   0.02067085274798998
Ni61   0.0009135482733530776
Ni62   0.0029605482553503814
Ni64   0.0007782038245561204
 
 [troubleshoot.pdf](https://github.com/pyne/pyne/files/3628142/troubleshoot.pdf)

**Comment by gonuke** [comment]
Thanks for submitting this.  It also appears that Mn has gone missing.  We'll investigate.

**Comment by gonuke** [comment]
Which version of PyNE are you using?  This does not happen in my version of PyNE

**Comment by petersondroogh** [comment]
pyne.__version__
'0.5.11'

**Comment by gonuke** [comment]
Closed due to update and impending release.
