### ISSUE TITLE
char* vs string 

### ISSUE THREAD

**Issue by bam241** [pyne/pyne#1181]
Developing the MaterialLibrary C++ API, this has been raised as a concern (by @pshriwise ).

here  is the quote of the beginning of the conversation from #1104 
If you have any though about this, please jump in.

@pshriwise :
>> * `std::string` vs. `char *` method definitions
>>   I'm presuming that these are to handle Python string → C++ string conversion, which is tricky, and I think this is about as good a way to handle it as any, but which methods are actually used external to the class in the `pyx/pxd` files is confusing right now. Maybe adding `_` to the front of the interally used methods ( i.e. `from_hdf5` → `_from_hdf5`) would help? It would just make the chain of calls easier to follow over all. If there's a mix of these calls externally, we might want to discuss why that is.

@bam241 :
>I tried to copy the material.hpp/cpp style. to implement both `char*` and `string` version of the methods.
>I am not sure about the C++ -> Python explanation, as we use both (in `Material` and `MaterialLibrary`...)
>Maybe it was poorly handle by python back in the day and is just a remaining of it.

>Long story short, I have no good explanation of using `char*` in place of `string`, maybe we should switch all of them to `string` ?

**Comment by pshriwise** [comment]
I think only using the `std::string` would be better if it's possible!

**Comment by gonuke** [comment]
My only question is whether this is due to some subtlety of cython that we are not appreciating?

**Comment by bam241** [comment]
this is very possible, but in the past we have been using both without issue...

reverting to one an other is not that hard (if we are able to pin point the issue...), so I incline to follow @pshriwise recommendation

**Comment by pshriwise** [comment]
@gonuke I'm not sure, but I think it's worth exploring unless those C-type signatures are being used elsewhere. Maybe @bam241 and I can sit down together at some point to sort it out. It may not be worth holding up #1104 at this time.

**Comment by gonuke** [comment]
Hmmm... I wonder if this is here to make things callable from C or FORTRAN?

**Comment by pshriwise** [comment]
Possibly! That would make sense. Is that done with PyNE anywhere that we know of?

**Comment by gonuke** [comment]
@pshriwise & @bam241 - is this resolved?

**Comment by pshriwise** [comment]
Looked through the `material_library.cpp` and `material_library.h` files and it looks like @bam did a nice job of using `std::string` wherever possible.
