### ISSUE TITLE
Material metdata: mat_name vs name

### ISSUE THREAD

**Issue by bam241** [pyne/pyne#1189]
Today with @pshriwise we spotted that in Material.cpp the openmc() methods expect the material name to be in the metadata as `mat_name` where all the other method uses `name`.

For consistency this has to be fixed.

But shall we break backward compatibility and suppress mention of `mat_name` or try to find a fix for it ?

**Comment by pshriwise** [comment]
If the other name methods were using `mat_name` before, we can probably just change the openmc method to use `name` and we'll be fine. I'll take that on as I was the one who added it in the first place. I'll also go ahead and remove `mat_name` from our test materials - unless there is some other reason for them to be there?

**Comment by pshriwise** [comment]
Looking at `material.cpp` further, maybe the metadata attribute to focus on is `mat_number`. Should that just be `number`?

**Comment by bam241** [comment]
that would make sense but again break backward compatibility

**Comment by pshriwise** [comment]
Yup.
