### ISSUE TITLE
Multi-particles tally definition

### ISSUE THREAD

**Issue by bam241** [pyne/pyne#1195]
I want/need to allow the `PyNE::Tally` to deal with multiple particles tallies.

It will ultimately only change the `std::string particle_name` into a `std::vector<std::string>` particles_name
(for the tally information data structure)

My problem is in the `write_hdf5` and `read_hdf5`, that now it is basically forming and writing:
```
typedef struct tally_struct {
    int entity_id;
    int entity_type;
    int tally_type;
    const char* particle_name;
    const char* entity_name;
    const char* tally_name;
    double entity_size;
    double normalization;
  } tally_struct;
```
into the hdf5 file.
I could probably replace the `const char*` with a `vector<const char*>` but I am not sure how to maintain backward compatibility.

I was thinking about concatenating the list of particle names into a single `string` with comma separator, allowing to write down a list of particle as a single `const char*`

Does it make sense ? What do you think ?

I wanted to have your though about this before I start the implementation of this part...

**Comment by gonuke** [comment]
closed by #1196
