### ISSUE TITLE
Error importing data from pyne

### ISSUE THREAD

**Issue by ananyashreyjain** [pyne/pyne#1215]
I used ```pip3 install pyne``` to install pyne.

Error:
```
ImportError: cannot import name 'data' from 'pyne' (/home/anany/me/venvs/tardis/lib/python3.7/site-packages/pyne.py)
```

**Comment by bam241** [comment]
Hi, I am unsure of which version you get while `pip install Pyne` this is not one of the supported way to install pyne.
when I tried it I got version 0.1.0 which is about 7y old :)

Also where do you get this error from ? I can't reproduce when importing `pyne` installed with `pip`

I would suggest either using `conda` or installing from source...

**Comment by ananyashreyjain** [comment]
Thanks for the quick response. Using ```from pyne import data``` gave this error. I think I will switch to conda to install pyne. I am closing this issue since using pip is not a supported way of installing pyne.
