### ISSUE TITLE
Material.decay_heat() RuntimeError

### ISSUE THREAD

**Issue by isabella897** [pyne/pyne#1217]
I am trying to use .decay_heat(), but I am getting a RuntimeError with a message of multiple black diamonds and random letters.  For context: I am testing it with a simple material, test = Material({'U238': 0.96, 'U235': 0.04}, 42) and defining the material is working fine as I can print the material data.  I'm doing this in Spyder in the PyNE ubuntu virtual machine.  Has anyone gotten this error/know how to fix this?

**Comment by gonuke** [comment]
Thanks for this feedback.  As a quick question, are you able to share the smallest snippet of code that reproduces this error?

Also, I think the virtualbox image is quite old (18 months), and perhaps needs to be updated.  Are you able to install PyNE in any other way?

**Comment by isabella897** [comment]
from pyne.material import Material
test = Material( { 'U238' : 0.96, 'U235' : 0.04}, 42)
decay = test.decay_heat()

I only have access to a Windows 10 machine currently.  Instead of the virtualbox, I could download the Windows subsystem for Linux and try installing PyNE on that if you think that would be better.

**Comment by gonuke** [comment]
This works in newer versions of PyNE.  I am not sure how well WSL will work with PyNE.  I wonder if @ljacobson64 has tried it?

We'll also see about getting a new virtualbox uploaded.

**Comment by ljacobson64** [comment]
I have successfully built PyNE on WSL, but I have not tested it. The installation procedure is identical to how one would install it on regular Linux. I would be very surprised if any of PyNE's functionality that is known to work on regular Linux didn't work on WSL.

**Comment by katyhuff** [comment]
This was fixed in a zoom call with screen sharing. 
Updating the source code from github, reinstalling, and rebuilding the database was sufficient to fix this issue.
