### ISSUE TITLE
Error in PyNE website documentation for .mcnp() method in material package

### ISSUE THREAD

**Issue by bohmt** [pyne/pyne#1219]
The documentation on the PyNE website for the .mcnp() method seems mis-written.  One can get a string to print an MCNP material card in either mass fraction (default) or atom fraction.  
.mcnp() prints by mass fraction
.mcnp('atom') prints by atom fraction

 The documentation on the web page says:

mcnp()

    Return an mcnp card Parameters ———-

        int 0 means use “mass” as the frac_type

**Comment by gonuke** [comment]
I believe this just requires rebuilding the site - the documentation has been improved/corrected at the source.

**Comment by gonuke** [comment]
Looks like @bam241 was the last to rebuild the website in June 2019

**Comment by bam241** [comment]
are you sure this is populated by the same section I tweaked ?
I can try to rebuild and see if there is any improvement...

**Comment by gonuke** [comment]
This was fixed by @ypark234 in #1211
