### ISSUE TITLE
Error in serpent.parse_dep's executable

### ISSUE THREAD

**Issue by ZoeRichter** [pyne/pyne#1224]
In serpent.py's function parse_dep, the function runs into an error when trying to execute the file to create the parsed depletion file.  After finding this error trying to run my own dep.m file, I ran the [HGTR single-pebble burnup example](http://serpent.vtt.fi/mediawiki/index.php/HTGR_fuel_pebble_burnup_example), to check that it wasn't simply my error.

>  ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-13-a61baff232d9> in <module>
> ----> 1 serpent.parse_dep('serpentexinput.inp_dep.m')
> 
> ~/.local/lib/python3.7/site-packages/pyne/serpent.py in parse_dep(depfile, write_py, make_mats)
>     286     # Execute the adjusted file
>     287     dep = {}
> --> 288     exec(f, dep, dep)
>     289     if '__builtins__' in dep:
>     290         del dep['__builtins__']
> 
> <string> in <module>
> 
> <string> in <listcomp>(.0)
> 
> ValueError: operands could not be broadcast together with shapes (44,) (16,) 

And still get the above error.

**Comment by katyhuff** [comment]
In your pyne build, is this only seen with output files involving triso particles? It seems like this be at the heart of the issue. 

@ZoeRichter I've assigned you because I know you'll be looking into it. Keep us posted in this issue.

**Comment by ZoeRichter** [comment]
I hadn't thought of that, so I just ran the [2D pin example](http://serpent.vtt.fi/mediawiki/index.php/2D_PWR_pin-cell_burnup_example), and I get the same kind of error:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-2-4a05379cd02f> in <module>
> ----> 1 serpent.parse_dep('serpentpinburn.inp_dep.m')
> 
> ~/.local/lib/python3.7/site-packages/pyne/serpent.py in parse_dep(depfile, write_py, make_mats)
>     286     # Execute the adjusted file
>     287     dep = {}
> --> 288     exec(f, dep, dep)
>     289     if '__builtins__' in dep:
>     290         del dep['__builtins__']
> 
> <string> in <module>
> 
> <string> in <listcomp>(.0)
> 
> ValueError: operands could not be broadcast together with shapes (21,) (27,) 

I forgot to mention before: My serpent version is 2.1.31
