### ISSUE TITLE
HDF5 1.12 Compatibility

### ISSUE THREAD

**Issue by efp** [pyne/pyne#1227]
Greetings,

I just tried a fresh build with HDF5 1.12, and there was one api compatibility issue, which I was able to solve by adding

`#define H5_USE_110_API`

before the project includes in **material.cpp.** 

It would probably be better to put that define in the build flags, or if there were a config.h type header, but I didn't see an easy way to do either of those things.

**Comment by gonuke** [comment]
Thanks for this comment @efp !  We have a fix for this that is nearly ready to be merged into the code in #1220
