### ISSUE TITLE
pytaps reference in the tutorials

### ISSUE THREAD

**Issue by bam241** [pyne/pyne#1240]
The tutorials still use the old `pyne.Mesh` implementation based on `pytaps`

for example the usage of `m.mesh.getVtxCoords(ve)` in the `00-intro` tutorial is outdated.

One ned to update the tutorials to the last `pyne.Mesh` implementation based on `pymoab`

**Comment by bam241** [comment]
@lkissin2 feel free to reply here if you find any additional related issue that seems somewhat related :)

**Comment by kkiesling** [comment]
So I have figured out the specific fix for this line, just needs to change to `m.mesh.get_coords(ve)` to match the PyMOAB call.

Though I am having other trouble with this tutorial as it relies on some yt stuff which relies on itaps which is pytaps.

**Comment by kkiesling** [comment]
I pip installed yt for this tutorial, so I did not expect this error. (Note, I am on python 2 because _reasons_ so this may not be an issue with python 3)

**Comment by kkiesling** [comment]
In reviewing the yt source code, it would appear that the MOAB/PyNE frontend there actually needs updating (last updated 5-7 years ago and relies on itaps still). It may be worth our while to update yt with the newer pyne and moab versions. (source code that is currently causing issues [here](https://github.com/yt-project/yt/blob/master/yt/frontends/moab/data_structures.py)).

**Comment by gonuke** [comment]
I wonder if @pshriwise has any thoughts on the yt issues?

**Comment by pshriwise** [comment]
I think @kkiesling has the right idea. It looks like there are two functions where `itaps` is imported. One looks like it can simply be removed. The other function has a call in it [here](https://github.com/yt-project/yt/blob/d00da5695bf5b9e29e9fdef97ef4f272ee69731e/yt/frontends/moab/data_structures.py#L128) which needs to be updated to an appropriate call in the PyNE Mesh API (whatever that may be, I'm not sure after a cursory glance). If that call doesn't exist via the `pyne.mesh` module then we should update `pyne.mesh` to make that possible.

**Comment by kkiesling** [comment]
[PR](https://github.com/yt-project/yt/pull/2856) has been issued in yt to address the yt Sliceplot errors.

**Comment by opotowsky** [comment]
PR #1282 closes this
