### ISSUE TITLE
Formatting of printing of materials not ideal

### ISSUE THREAD

**Issue by opotowsky** [pyne/pyne#1277]
Before the material library changes, the following command printed:
`list(mats.keys())[:10]`

```
['Mercury',
 'Oil, Crude (Heavy, Qayarah, Iraq)',
 'Sm',
 'Lead',
 'Concrete, M-1',
 'Sc',
 'Iron, Armco Ingot',
 'Freon-13',
 'Concrete, Luminite-colemanite-baryte',
 'Air (dry, near sea level)']
```

And now it prints as such (it's sorted now, which is no big deal, but the outputs are different):
```
[b'Au',
 b'Ar',
 b'As',
 b'Zirconium Hydride (Zr5H8)',
 b'Bone, Compact (ICRU)',
 b'Plutonium Nitrate',
 b'Boral (Aluminum 5% boron alloy)',
 b'Earth, U.S. Average',
 b'Nylon, Type 11 (Rilsan)',
 b'Boron']
```

Is this important? Do we care?

**Comment by gonuke** [comment]
Where do you see this?  It might be a consequence of the Py3 update, rather than the MaterialLib update....

**Comment by gonuke** [comment]
That is - where do you see the old version?  in an old Notebook?

**Comment by opotowsky** [comment]
Yep -- closing the issue since it is py3 and not material-lib!
