### ISSUE TITLE
Update the zip and tar files after the release of 0.7.0

### ISSUE THREAD

**Issue by nsryan2** [pyne/pyne#1278]
Currently, the links that download .zip and .tar source code for PyNE go to the 0.5.10 files. Following the release and finalization of 0.7.0, the links should be changed for the source install instructions to download the current version. These files, following the release of the update, can be found by going to the default branch, clicking on tags at the top, and then copying the archive links for zip and tar under the 0.7.0 tag.

**Comment by bam241** [comment]
closing at it is redundant with #1313
