### ISSUE TITLE
nuc_data_make not supported on Ubuntu 20.04 with python3

### ISSUE THREAD

**Issue by kkiesling** [pyne/pyne#1306]
I am trying to build PyNE on an Ubuntu 20.04 image. The build is successful until `nuc_data_make` when the it hits an error because it can't find the executable `python`. Ubuntu 20.04 only comes with a `python3` executable and no `python` or `python2` executable. The `nuc_data_make` script needs to be updated to find the correct python executable and use that whether that is `python`, `python2`, or `python3`.

I don't know exactly where this error occurs in the script, but I will do some more sleuthing and see if I can figure it out. Making the issue in case anyone else immediately knows where this needs fixed.

**Comment by kkiesling** [comment]
This might actually be as simple as just running `python3 ./scripts/nuc_data_make` instead of simply `./scripts/nuc_data_make`.

**Comment by gonuke** [comment]
Your fix will prob work, in our build process, but is is interesting that U20.04 chose to break this longstanding capability:
`#!/usr/bin/env python` that is specifically designed to help resolve this.
One solution is this:
https://linuxconfig.org/ubuntu-20-04-python-version-switch-manager
That gives a safe way to alias python to python3 (or 2 as the case may be)

**Comment by gonuke** [comment]
Apparently there's also a `python-is-python3` package to apt install?

**Comment by kkiesling** [comment]
> Your fix will prob work, in our build process, but is is interesting that U20.04 chose to break this longstanding capability:
> `#!/usr/bin/env python` that is specifically designed to help resolve this.
> One solution is this:
> https://linuxconfig.org/ubuntu-20-04-python-version-switch-manager
> That gives a safe way to alias python to python3 (or 2 as the case may be)

this update-alternatives is actually what @bam241 implemented in our svalinn/dockerfiles for python3. It's worth probably doing that in a docker image or VM but probably not in a standard build script. I don't think we should be setting that in people's systems.

**Comment by gonuke** [comment]
Can we close this @kkiesling ?

**Comment by kkiesling** [comment]
Oh yes. Forgot about it.
