### ISSUE TITLE
File format versioning for R2S (and all?) output files.

### ISSUE THREAD

**Issue by pshriwise** [pyne/pyne#1349]
The output files of R2S (as of #1341 I think this may be only the photon source file) are subject to occasional change. It seems to me that workflows and applications relying on these files would benefit from the addition of version numbers to ensure that a certain format specification can be expected and compatibility with other applications can be ensured.

I'm not as familiar with it anymore, but it seems like this would likely benefit the `MaterialLibrary` as well.

**Comment by zxkjack123** [comment]
@pshriwise Can't agree more. The version conflicts happens frequently for me. A pyne version number (x.xx.xx) is not enough to identify the specific version as many it covers many PRs. Maybe the id of the last PR or the hash id of the commit is a good choice of version tag.

**Comment by pshriwise** [comment]
Glad to hear you're on board! I think the most common practice is to update the version numbers only when code changes are merged that change the information or organization of the file.

**Comment by zxkjack123** [comment]
Close this PR as file format version has been tagged to `source.h5m` in #1352 .
