### ISSUE TITLE
Release numbers in latest microreleases

### ISSUE THREAD

**Issue by alexmalins** [pyne/pyne#1354]
**Describe the Bug**<br/>
Release numbers not getting updated in the latest microreleases (0.7.2 & 0.7.3).

**To Reproduce**<br/>
```
>>> import pyne
>>> pyne.__version__
'0.7.1'
```

**Expected Behavior**<br/>
```
>>> import pyne
>>> pyne.__version__
'0.7.3'
```

**Screenshots or Code Snippets**<br/>
N/A

**Please complete the following information regarding your system:**<br/>
 - OS: WSL Ubuntu 20.04
 - PyNE Version: 0.7.3
 - Versions of dependencies installed with: N/A

**Additional Context**<br/>
A quick way to find all the release numbers in the sort code and update them is to run `grep -rnw . -e '0\.7\.1'` in the PyNE source directory. This lists all the locations in the source where the release numbers need to be updated:
```
./.github/ISSUE_TEMPLATE/bug-report.md:27: - PyNE Version: [e.g. 0.7.1]
./docs/install/conda.rst:31:For example, if you want to install ``pyne version=0.7.1`` with build option ``moab_openmc``, you would enter::
./docs/install/conda.rst:33:    conda install -c conda-forge pyne=0.7.1=moab_openmc*
./docs/install/source.rst:106:.. _zip: https://github.com/pyne/pyne/zipball/0.7.1
./docs/install/source.rst:107:.. _tar: https://github.com/pyne/pyne/tarball/0.7.1
./pyne/__init__.py:5:__version__ = '0.7.1'
./setup.py:63:VERSION = '0.7.1'
./setup_sub.py:26:VERSION = '0.7.1'
./src/utils.cpp:16:std::string pyne::VERSION = "0.7.1";
```
When I created PR #1326 to update the release numbers for 0.7.1, this is basically what I did. Happy to create another PR to update all the numbers again, but creating this issue as a prompt to the team as ideally the numbers should be updated before every release as a matter of process.

**Comment by gonuke** [comment]
Yikes!  It happened again - sorry @alexmalins 

Perhaps someone can take a run at automating some of this from a single version string, perhaps the one in `setup.py`?

**Comment by alexmalins** [comment]
I had a quick look around and some projects are using packages like [versioneer](https://pypi.org/project/versioneer/) or [bump2version](https://pypi.org/project/bump2version/) for updating release numbers. Some discussion [here](https://www.reddit.com/r/Python/comments/47d7ll/automatically_increment_version_on_package_release/). Complicating factor for PyNE is it's not pure Python, but a mix of multiple languages.

Other solutions seem to take the version in `setup.py` and update the versions in other source files when `setup.py` is run. This is probably not ideal as the version numbers in the docs should be up to date in the release source tarball, rather than updated when individual users run `setup.py`.

A quick [one line](https://stackoverflow.com/questions/11392478/how-to-replace-a-string-in-multiple-files-in-linux-command-line/11392505) way to update the numbers in all source files in one go is `grep -rli '0\.7\.1' * | xargs -i@ sed -i 's/0\.7\.1/0\.7\.3/g' @`. However regex expression like this are quite dangerous so not a good long-term solution.

**Comment by alexmalins** [comment]
Looks like #1434 & #1415 have simplified the version numbering by bringing everything into one place (`pyne/pyne_version.py`) 👍
