### ISSUE TITLE
FAIL: Test total energy group MAGIC case

### ISSUE THREAD

**Issue by bam241** [pyne/pyne#1365]
@pshriwise any idea why this is failing ?
https://app.circleci.com/pipelines/github/pyne/pyne/1246/workflows/6660881a-d998-402e-b4a9-e9ba7d366a45/jobs/11810
```
======================================================================
FAIL: Test total energy group MAGIC case
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/root/repo/tests/test_variancereduction.py", line 187, in test_magic_e_total
    assert_array_almost_equal(tally.ww_x[:], expected_ww[:])
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 1044, in assert_array_almost_equal
    precision=decimal)
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals

Mismatched elements: 1 / 4 (25%)
Max absolute difference: 0.16060606
Max relative difference: 0.88333333
 x: array([0.021212, 0.5     , 0.242424, 0.001   ])
 y: array([0.181818, 0.5     , 0.242424, 0.001   ])

----------------------------------------------------------------------
Ran 5 tests in 0.032s

FAILED (failures=1)
Testing failed on test_variancereduction.py
```
it failed after merge of #1358 (I restarted it 3 times...)

**Comment by pshriwise** [comment]
Hrmm, I'm can't see why the changes from #1358 would cause a failure in this test. It seems like an entirely unrelated area of the code. 

FWIW I was trying this out locally and did manage to get `test_variancereduction.py` to fail in the same way once, but it seems that it's extremely rare. After noting that I tried restarting CI one more time and it did pass all of the tests 

https://app.circleci.com/pipelines/github/pyne/pyne/1246/workflows/bc0d075e-d699-483f-b37b-0a51de8a2320

Is it possible that we're uncovering a test that has been randomly failing for some time?

**Comment by ahnaf-tahmid-chowdhury** [comment]
Does this issue still persist?

**Comment by gonuke** [comment]
I vaguely recall that this random, rare test failing went away, so I think we can close this @bam241

**Comment by bam241** [comment]
I think we can. 
It might have been fixed, as well...

And one can always reopen it if this occurs again.
