### ISSUE TITLE
struct.unpack error

### ISSUE THREAD

**Issue by pinghanchu** [pyne/pyne#1373]
**Describe the Bug**<br/>
Successfully install PyNE.  However, while reading a ptrac data by using "pyne.mcnp.PtracReader(filename)", the program complains as "error: unpack requires a buffer of 538981924 bytes". Check the PyNE code itself. The error happens to the Line 1124 in mcnp.py, " tmp = struct.unpack(b"".join([self.endianness.encode(),(format*number).encode(), b'i']), b)" . 

**Screenshots or Code Snippets**<br/>
<img width="775" alt="Screen Shot 2021-04-19 at 3 27 22 PM" src="https://user-images.githubusercontent.com/10731275/115305599-d090a600-a123-11eb-90df-f4b3fb3e4ca7.png">
The ptrac file looks like:
<img width="866" alt="Screen Shot 2021-04-19 at 3 33 26 PM" src="https://user-images.githubusercontent.com/10731275/115306138-9bd11e80-a124-11eb-9326-ff0f855fe566.png">

**Please complete the following information regarding your system:**<br/>
 - OS: MacOS 10.13.6
 - PyNE Version: pyne  0.7.0   nomoab_noopenmc_py37h351adfa_1    conda-forge

**Comment by gonuke** [comment]
Thanks for submitting this issue.

First, I want to let you know that this version of PyNE is not well-supported for MacOS on conda-forge.  Hopefully, we can produce a newer version soon.

Your problem, however, is that the PTRAC reader in PyNE is designed for *binary* PTRAC files and you are attempting to read an ASCII (non-binary) file.

**Comment by pinghanchu** [comment]
Thanks for the suggestion. Unfortunately, PyNE.mcnp.PtracReader still cannot read the binary ptrac file. I wonder this is due to the MacOS. The error is attached. 

<img width="735" alt="Screen Shot 2021-04-20 at 3 38 59 PM" src="https://user-images.githubusercontent.com/10731275/115467428-bc65ab00-a1ee-11eb-8dfa-70318c8cc0a8.png">

**Comment by bam241** [comment]
I believe this has been fixed in #1336

sadly the fix is not part of PyNE:0.7 and we dropped support of macOS for conda on 0.7.1 :(

you probably will need to build PyNE yourself

(in the mean time I'll check why we disabled macOS on conda...)

**Comment by gonuke** [comment]
Closing this with a note that we need to revisit MacOS support  in conda at a future release.
