### ISSUE TITLE
Update materials to newest version of the compendium

### ISSUE THREAD

**Issue by gonuke** [pyne/pyne#1379]
A new version of the materials compendium published by PNNL has been released: https://compendium.cwmd.pnnl.gov/

A JSON version of the data is available on this site.  We should create a method that will parse this JSON data and create a material library for distribution with PyNE.

**Comment by ahnaf-tahmid-chowdhury** [comment]
Dear @gonuke, I've checked the new materials compendium published by PNNL. I agree with your suggestion to create a method that parses this JSON data and generates a material library for distribution with PyNE. However, I have a few questions before we proceed.

- Could you please confirm if the website contains all the information included in the materials compendium? It's important to ensure that we have access to all the necessary data before making any decisions regarding the existing method.

- Considering the availability of this new data source, do we need to entirely replace the previous method, or should we create a new method specifically for parsing the JSON data from this website? Understanding the relationship between the existing method and the new data source will help us determine the best approach for implementation.

**Comment by gonuke** [comment]
> Dear @gonuke, I've checked the new materials compendium published by PNNL. I agree with your suggestion to create a method that parses this JSON data and generates a material library for distribution with PyNE. However, I have a few questions before we proceed.
> 
> * Could you please confirm if the website contains all the information included in the materials compendium? It's important to ensure that we have access to all the necessary data before making any decisions regarding the existing method.

I just took a quick look at the JSON and it seems very comprehensive, perhaps with more data than we had available historically.  

> * Considering the availability of this new data source, do we need to entirely replace the previous method, or should we create a new method specifically for parsing the JSON data from this website? Understanding the relationship between the existing method and the new data source will help us determine the best approach for implementation.

I think we want a new method to read this particular matadata layout/format.  We could then include a line to fetch the JSON file at build time to ensure an up-to-date data source with each install (as we do with some other data sources today).

**Comment by ahnaf-tahmid-chowdhury** [comment]
Closing this issue as we have [materials-compendium](https://github.com/pyne/materials-compendium).
