### ISSUE TITLE
PyNE Installation from Conda

### ISSUE THREAD

**Issue by ronlgithub** [pyne/pyne#1381]
I am trying to install the PyNE package on my Windows 10 computer.
When I use this script listed on the PyNE site I get an error message:
conda install -c conda-forge pyne

(base) C:\Users\ron>conda install -c conda-forge pyne
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyne

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

When I use this script:
conda search -c conda-forge pyne
I get a message that says  No match found for: pyne. Search: *pyne*
and then a list of packages.

(base) C:\Users\ron>conda search -c conda-forge pyne
Loading channels: done
No match found for: pyne. Search: *pyne*
# Name                       Version           Build  Channel
pynetdicom                     1.4.1    pyh8c360ce_0  conda-forge
pynetdicom                     1.5.0    pyh9f0ad1d_0  conda-forge
pynetdicom                     1.5.1    pyh9f0ad1d_0  conda-forge
pynetdicom                     1.5.2    pyh9f0ad1d_0  conda-forge
pynetdicom                     1.5.3    pyh9f0ad1d_0  conda-forge
pynetdicom                     1.5.4    pyhd3deb0d_0  conda-forge
pynetdicom                     1.5.5    pyhd3deb0d_0  conda-forge
pynetdicom                     1.5.6    pyh44b312d_0  conda-forge
pynetdicom                     1.5.6    pyhd8ed1ab_1  conda-forge
pynetdicom                     1.5.7    pyhd8ed1ab_0  conda-forge
pynetworktables             2021.0.0    pyhd8ed1ab_0  conda-forge
spyne                        2.12.11          py27_0  conda-forge
spyne                        2.12.11          py34_0  conda-forge
spyne                        2.12.11          py35_0  conda-forge
spyne                        2.12.13          py27_0  conda-forge
spyne                        2.12.13          py34_0  conda-forge
spyne                        2.12.13          py35_0  conda-forge
spyne                        2.12.14          py27_0  conda-forge
spyne                        2.12.14          py34_0  conda-forge
spyne                        2.12.14          py35_0  conda-forge
spyne                        2.12.14       py36_1000  conda-forge
spyne                        2.12.16          py27_0  conda-forge
spyne                        2.12.16          py36_0  conda-forge
spyne                        2.12.16            py_1  conda-forge
spyne                        2.13.16    pyhd8ed1ab_0  conda-forge

What do I need to do to install PyNE

Thanks
ronlinmd@gmail.com

**Comment by gonuke** [comment]
Thanks for bringing this up again @ronlgithub. We do not have a lot of experience with building PyNE on Windows and don't officially support it yet.

**Comment by gonuke** [comment]
I think some users have been successful in installing PyNE in the Windows Subsystem for Linux (WSL), which allows them to use PyNE in what is nominally the same environment as they run other things in Windows.

**Comment by alexmalins** [comment]
This was discussed on the MCNP users group, but I am summarizing here for others. There are three reported options for running PyNE on Windows:

1. Installing PyNE from source on Windows Subsystem for Linux (WSL) and Ubuntu - notes here: https://alexmalins.com/blog/installing-pyne-on-windows-via-wsl/
2. Installing PyNE via Anaconda on Windows Subsystem for Linux (WSL) and Ubuntu - relevant links [[1](https://groups.google.com/g/pyne-dev/c/dJVAc6K4L7w)], [[2](https://groups.google.com/g/pyne-dev/c/MzhxFaYA9N4)], [[3](http://mmb.irbbarcelona.org/molywood/tutorials/windows_sub)]
3. Using the PyNE [VirtualBox](https://pyne.io/install/vb.html)

I have tested both options 1 and 2, and 2 was probably the easiest of those two.
Option 3 has the benefit of not requiring Windows administrator privileges. The current PyNE VirtualBox version (0.7.0) looks to be a little behind the latest (0.7.3), however.
