### ISSUE TITLE
FORTRAN build failures with GCC 10+

### ISSUE THREAD

**Issue by gonuke** [pyne/pyne#1416]
**Describe the Bug**<br/>
The default behavior of GCC 10+ is to identify inconsistencies between argument types in multiple calls to the same method, and call it an error.  In many cases, there are well-defined ways for one type to substitute for another and it is debatable whether or not it is an error.

**To Reproduce**<br/>
Try to build with FORTRAN on and GCC 10 or higher.

**Expected Behavior**<br/>
successful build

**Screenshots or Code Snippets**<br/>
See reports in mailing list: https://groups.google.com/g/pyne-dev/c/Tm-5ZQwlCw8

**Additional Context**<br/>
Some reputable projects, e.g. MPICH, have adopted a work around : https://lists.mpich.org/pipermail/discuss/2020-January/005863.html

**Comment by ohnemax** [comment]
I just stumbled into the same issue (error with "alphad" compilation). Based on the information above, I was able to find a work-around:

Add the line
`SET(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -fallow-argument-mismatch")`
to the `CMakeLists.txt` in the main folder.

I am not sure whether this is worth a pull request (or even good), as it just circumvents the error from being flagged.

**Comment by gonuke** [comment]
Thanks for following up with an issue here @ohnemax - I'd welcome a pull request to with the suggestion you made above.  I think this code is old enough that this is the best way to fix it.  You could perhaps make this change only in the `CMakeLists.txt` file in the folder where the offending code is - that might be a little cleaner.

Incidentally, I think the default for PyNE should be to build without these tools - have you turned them on explicitly?

**Comment by ahnaf-tahmid-chowdhury** [comment]
Does this issue still persist? In that case I can make a PR to solve this.

**Comment by gonuke** [comment]
I think it does still persist - feel free to PR a solution
