### ISSUE TITLE
ImportError: /usr/local/lib/libpyne.so: Undefined symbol "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev"

### ISSUE THREAD

**Issue by yurivict** [pyne/pyne#1419]
Assembly files cram-linux-clang.s and decay-linux-clang.s contain wrong STL symbols that cause the error from the subject.

How to rebuild them from source code to solve this issue?

Version: 0.7.5
Python-3.8
FreeBSD 13

**Comment by gonuke** [comment]
I think this will happen if you add `--slow` when you run `setup.py`

**Comment by yurivict** [comment]
This works. Thanks!
