### ISSUE TITLE
Clarify strategy matrices for docker_publish workflow

### ISSUE THREAD

**Issue by gonuke** [pyne/pyne#1425]
The `docker_publish` Github Action workflow has many steps, three of which operate over a set of different options defined with a `matrix`.  Each of the three `matrix` objects is slightly different.  While there may be a reason for some of these to be different, one of those differences is probably the source of the workflow failing at the (almost) last step.

A careful review of the three matrices should be conducted to confirm the "correct best" set of variations to be building and to document any cases where those matrices are/should be different.

**Comment by bam241** [comment]
AS explain in #1426 I believe the building strategy is:

the first job builds the following option:

py3
py3+pymoab+apt-hdf5
the second one:

py3+pymoab+dagmc(+apt-hdf5)
py3+pymoab+dagmc+hdf5-1.12
py3+pymoab+dagmc(+apt-hdf5)+openmc

**Comment by gonuke** [comment]
resolved in #1426 

Thanks for chiming in @bam241
