### ISSUE TITLE
Documentation Gamma function - factor 100

### ISSUE THREAD

**Issue by cfichtlscherer** [pyne/pyne#1433]
In the documentation, it is stated that the method material.gammas() "Returns a vector of gamma rays and intensities in decays/s/atom material". I think we should note here that this value refers to per 100 decays. 

So, for example, when I run this method on the material consisting only out of Cs-137, it will return
`(283.5, 4.2351778792770855e-13)`
`(661.657, 6.214028233215172e-08)`

(the first value is the energy of the gamma in keV, and the second value is the intensity. From the documentation you would think the intensity is given in [decays/s/atom], but actually it is given in [100*decays/s/atom])

When I compare this with calculations with the data from [nucleide.org](http://www.nucleide.org/Laraweb/index.php) for the 661.657 keV peak of Cs-137 I get the following:
Specific activity (Am): 3.213 *10e12 [Bq/g] [decays/g/s]   
The intensity is given with 84.99% (note this is another intensity, it states in how many percent of decays this emission will occur).

Specific activity * intensity * mass-cs-137 / mol  = 6.212239912837907e-10 [decays/s/atom]

Maybe I am doing a mistake here, but I am quite sure, there is an error by a factor of 100. Instead of changing the documentation, we could also change the code directly.

**Comment by ahnaf-tahmid-chowdhury** [comment]
Hi @cfichtlscherer, I am assuming that dividing the value by 100 in the code snippet may potentially resolve the issue, but I'm unsure if this is the most robust solution. If you have any alternative approaches in mind, please let me know. I'm open to creating a PR with the suggested changes.

```c++
// material.cpp
std::vector<std::pair<double, double> > pyne::Material::gammas() {
  std::vector<std::pair<double, double> > result;
  std::map<int, double> atom_fracs = this->to_atom_frac();
  int state_id;
  for (comp_iter ci = comp.begin(); ci != comp.end(); ci++) {
    if (ci->first % 10000 > 0)
        state_id = nucname::id_to_state_id(ci->first);
    else
        state_id = ci->first;

    std::vector<std::pair<double, double> > raw_gammas = pyne::gammas(state_id);
    for (int i = 0; i < raw_gammas.size(); ++i) {
      result.push_back(std::make_pair(raw_gammas[i].first,
        atom_fracs[ci->first]*(raw_gammas[i].second/100)));  // Divide by 100 for intensity correction
    }
  }
  return result;
}
```

**Comment by cfichtlscherer** [comment]
Hi @ahnaf-tahmid-chowdhury, yes that would be a way. And in addition I think the documentation should be more clear.

**Comment by cfichtlscherer** [comment]
Thanks a lot for taking care of this!
