### ISSUE TITLE
Nose not supported with python 3.10

### ISSUE THREAD

**Issue by ngranda** [pyne/pyne#1453]
**Describe the Bug**<br/>
Nosetest is deprecated and no longer supported with python 3.10. Update to pytest might be needed 

**To Reproduce**<br/>
Building PyNE on Ubuntu 22.04 with python 3.10 cannot run tests. The problem can be reproduced with the docker file [here](https://github.com/ngranda/install_scripts/blob/ubuntu22.04/ubuntu_22.04-stable.dockerfile) 

**Expected Behavior**<br/>
Tests should pass

**Please complete the following information regarding your system:**<br/>
 - OS: Ubuntu22.04
 - PyNE Version: 0.7.7
 - Versions of dependencies installed with: hdf5 1.10.7, python 3.10, nose 1.3.7, moab 5.3

**Comment by ahnaf-tahmid-chowdhury** [comment]
From Python v3.10, `Callable` object is removed from `collections` class. It is now moved to `collections.abc` class.

You may need to replace this in `suite.py` and `case.py`:

    import collections

To:

     import collections.abc

**Comment by gonuke** [comment]
Resolved in #1478
