### ISSUE TITLE
Move standard installation script into main PyNE repo for regular testing

### ISSUE THREAD

**Issue by gonuke** [pyne/pyne#1462]
The PyNE team has historically maintained a separate repository with installation scripts for different platforms: [pyne/install_scripts](https://github.com/pyne/install_scripts).

The scripts in this repo frequently fall out of sync with the state of the main code repository, causing frustration for users.  It will be better to provide such a script as part of this repository, and add an action that forces that/those scripts to be tested with each PR to ensure that those scripts are updated as appropriate with each code addition.

**Comment by gonuke** [comment]
While I had a conversation about this with @ngranda, it might make more sense for @bquan0 to take this on.

I think the best way to make an install script is to use the sequence of commands that are in the current `Dockerfile` and implement them as a stand-alone bash script.

Then we need to add a workflow that runs this script.  I think there may be some open questions about which version of the code should be tested with this script.  Perhaps the script should only be updated with a release?

**Comment by ahnaf-tahmid-chowdhury** [comment]
Certainly, it is possible to use both Docker and a Python environment such as venv in a development workflow. In fact, using both can provide the best of both worlds in terms of flexibility, isolation and portability.

Docker allows for creating a standardized and portable runtime environment for an application, making it easy to move between different environments and ensuring consistency. Meanwhile, a Python environment such as venv can provide a lightweight and isolated environment for testing and developing code, avoiding conflicts with other packages and ensuring the application runs as intended. By using both, it is possible to take advantage of the benefits of each approach to create a robust and effective development workflow that meets the needs of the project and the team.

When considering the use of bash scripting for installation, it may be beneficial to provide users with the ability to choose which modules to install. This can help ensure that only the necessary modules are installed, streamlining the process and potentially saving disk space.

That being said, it is important to note that DAGMC supports Geant4. Therefore, it may also be worthwhile to include the option for users to include Geant4 in the same environment. This would allow users to benefit from the full functionality of DAGMC and Geant4 without the need for separate installations.

By providing users with flexibility in the installation process and ensuring that all necessary dependencies are included, we can create a more streamlined and efficient workflow for the development and use of DAGMC.

**Comment by gonuke** [comment]
I think it is reasonable to support a variety of installation script variations, but we should consider these high-level philosophical points:
1. Will too many variations be confusing to potential users? Can we provide adequate documentation to help users find what they need?
2. There is maintenance burden with updating multiple installation scripts, so we should find the right balance on this front, as well.
3. The multitude of options with upstream dependencies already creates some challenges in terms of how to share installation instructions.  Adding options for each of those dependencies makes this more complicated.
4. At what point do we assume that a user is sufficiently knowledgeable to use general instructions and install themselves rather than use our build script - this almost certainly requires a documentation update!

**Comment by ahnaf-tahmid-chowdhury** [comment]
You make some excellent points. It is important to strike a balance between providing users with the flexibility they need and avoiding confusion and maintenance burden. One way to achieve this is to provide a set of standard installation scripts that cover the most common use cases, while also providing documentation that explains how to customize these scripts for less common scenarios.

In terms of documentation, it may be helpful to provide clear instructions and examples for each installation option, as well as detailed explanations of the dependencies and how they are used. Additionally, it may be useful to provide a troubleshooting guide that helps users identify and resolve common installation issues.

Regarding the question of when to assume that a user is sufficiently knowledgeable to install the software themselves, it may be beneficial to provide both a detailed guide for beginners and more concise instructions for experienced users. This can help ensure that the installation process is accessible to a wide range of users, while also allowing more experienced users to quickly install the software without being burdened with unnecessary details. Providing a Bash script that automates the installation process and provides instructions can be a great way to streamline the process for users. The script can be designed to automatically download and install all necessary dependencies, including any optional dependencies that the user may choose to include. The script can also include instructions on how to customize the installation process, such as choosing which modules to install and where to install them.

Ultimately, the goal should be to provide users with a clear and streamlined installation process that meets their needs while also minimizing confusion and maintenance burden.

**Comment by gonuke** [comment]
This was resolved in #1477
