### ISSUE TITLE
Compilation Error on Windows in `enrichment_symbolic.cpp`

### ISSUE THREAD

**Issue by ahnaf-tahmid-chowdhury** [pyne/pyne#1506]
## Description
I encountered a compilation error when trying to build PyNE with Windows support. The error occurs in the `enrichment_symbolic.cpp` file. I am using MinGW to build the project, and the error message is as follows:

```make
[ 20%] Building CXX object src/CMakeFiles/pyne.dir/enrichment_symbolic.cpp.obj
mingw32-make.exe[2]: *** [src\CMakeFiles\pyne.dir\build.make:345: src/CMakeFiles/pyne.dir/enrichment_symbolic.cpp.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:203: src/CMakeFiles/pyne.dir/all] Error 2
mingw32-make.exe: *** [Makefile:135: all] Error 2
```

## Steps to Reproduce
To reproduce this issue, follow these steps:
1. Clone the [my PyNE repository](https://github.com/ahnaf-tahmid-chowdhury/PyNE/tree/scikit-build).
2. Build the project with Windows support using MinGW.
3. Run `python -m pip install .` to install PyNE.
4. Observe the compilation error in the `enrichment_symbolic.cpp` file.

## Expected Behavior
The project should compile successfully on Windows with MinGW.

## Environment
- Operating System: Windows latest
- Compiler: MinGW
- PyNE Version: Dev

**Comment by gonuke** [comment]
Did you receive more info in the error message?  Do you know what "Error 1" means? (I don't think that's a MingGW compiler  error?)

**Comment by ahnaf-tahmid-chowdhury** [comment]
It seems it's not providing more info log. `Error 1` doesn't provide specific information about the nature of the error, it's a way of signaling to the user that something went wrong. However, Ubuntu is passing this same code.

**Comment by ahnaf-tahmid-chowdhury** [comment]
I have solved the issue
