### ISSUE TITLE
Build fails: error: no member named 'std' in namespace 'std'; did you mean simply 'std'?

### ISSUE THREAD

**Issue by yurivict** [pyne/pyne#1517]
**Describe the Bug**<br/>
```
In file included from /wrkdirs/usr/ports/science/py-PyNE/work-py39/pyne-0.7.7/build/pyne/ace.cxx:1017:
/usr/include/c++/v1/complex:1404:48: error: no member named 'std' in namespace 'std'; did you mean simply 'std'?
 1404 |     if (__x.real() == 0 && (__x.imag() == 0 || std::isnan(__x.imag())))
      |                                                ^
```

[log](https://pkg-status.freebsd.org/beefy18/data/main-amd64-default/paac5a117b85a_s08efe9bef4/logs/py39-PyNE-0.7.7_4.log)

These lines in src/utils.h cause this problem:
```
#if (__GNUC__ >= 4)
  #include <cmath>
  #define isnan(x) std::isnan(x)
#else
  #include <math.h>
  #define isnan(x) __isnand((double)x)
#endif
```

Removing these lines makes the problem to go away.

There should be no need to deviate from the C++ standard: ```#include <cmath>``` is what should be used in C++ and there is no need to define ```isnan```. If it isn't present - the distro has to fix that instead of everyone working around this problem.

**To Reproduce**<br/>
regular build

**Please complete the following information regarding your system:**<br/>
 - OS: FreeBSD 14.0
 - PyNE Version: 0.7.7
- compiler: clang-16

**Comment by gonuke** [comment]
Thanks for your feedback @yurivict.  We noticed this a few months ago as well, and it was resolved in #1502 for release 0.7.8.

**Comment by gonuke** [comment]
I've reopened this so that you can decide if this resolved the issue @yurivict

**Comment by yurivict** [comment]
I am confirming that this problem is gone in 0.7.8

Thank you!
