### ISSUE TITLE
Error when compiling Cython CXX source for enrichment in Pyne 0.7.8

### ISSUE THREAD

**Issue by tom-neville** [pyne/pyne#1520]
**Describe the Bug**<br/>

Error when installing Pyne 0.7.8 from source code. The error occurs when compiling Cython file enrichment.pyx. Error details are in the Screenshots or Code Snippets section below. Make then fails with Error 2.

**To Reproduce**<br/>

Using Anaconda
conda create --name pyne numpy scipy cython h5py pytables jinja2 jupyter sphinx prettytable numpydoc
conda activate pyne
conda install -c conda-forge lapack
pip install sphinxcontrib-bibtex
mkdir pyne
cd pyne
 wget https://github.com/pyne/pyne/archive/refs/tags/0.7.8.zip
unzip 0.7.8.zip
cd pyne-0.7.8
python setup.py install --hdf5 /path/to/anaconda3/pkgs/hdf5-1.12.1-h2b7332f_3

**Expected Behavior**<br/>

Successful build of Pyne 0.7.8.

**Screenshots or Code Snippets**<br/>

[ 58%] Compiling Cython CXX source for enrichment...

Error compiling Cython file:

------------------------------------------------------------
...
            return self._mat_feed

        def __set__(self, value):
            cdef pyne.material._Material value_proxy
            value_proxy = pyne.material.Material(value, free_mat=not isinstance(value, pyne.material._Material))
            (<cpp_enrichment.Cascade *> self._inst).mat_feed = value_proxy.mat_pointer[0]
                                                                                      ^
------------------------------------------------------------

/path/to/pyne/pyne-0.7.8/pyne/enrichment.pyx:183:86: Cannot assign type 'Material &' to 'Material'

Error occurs three times in succession, for _mat_feed, _mat_prod, and _mat_tail.

**Please complete the following information regarding your system:**<br/>

Ubuntu on WSL2

gcc version 11.4.0
gfortran version 11.4.0
CMake version 3.22.1

Conda environment with following packages and versions
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
alabaster                 0.7.12             pyhd3eb1b0_0
anyio                     4.2.0           py311h06a4308_0
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0          py311h5eee18b_0
asttokens                 2.0.5              pyhd3eb1b0_0
async-lru                 2.0.4           py311h06a4308_0
attrs                     23.1.0          py311h06a4308_0
babel                     2.11.0          py311h06a4308_0
beautifulsoup4            4.12.2          py311h06a4308_0
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
blosc                     1.21.3               h6a678d5_0
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.19.1               h5eee18b_0
c-blosc2                  2.12.0               h80c7b02_0
ca-certificates           2024.2.2             hbcca054_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py311h5eee18b_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
colorama                  0.4.6           py311h06a4308_0
comm                      0.1.2           py311h06a4308_0
cyrus-sasl                2.1.28               h52b45da_1
cython                    3.0.6           py311h5eee18b_0
dbus                      1.13.18              hb2f20db_0
debugpy                   1.6.7           py311h6a678d5_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
docutils                  0.17.1                   pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0
expat                     2.5.0                h6a678d5_0
fontconfig                2.14.1               h4c34cd2_2
freetype                  2.12.1               h4a9f257_0
glib                      2.69.1               he621ea3_2
gst-plugins-base          1.14.1               h6a678d5_1
gstreamer                 1.14.1               h5eee18b_1
h5py                      3.9.0           py311hdd6beaf_0
hdf5                      1.12.1               h2b7332f_3
icu                       73.1                 h6a678d5_0
idna                      3.4             py311h06a4308_0
imagesize                 1.4.1           py311h06a4308_0
intel-openmp              2023.1.0         hdb19cb5_46306
ipykernel                 6.28.0          py311h06a4308_0
ipython                   8.20.0          py311h06a4308_0
ipywidgets                8.0.4           py311h06a4308_0
jedi                      0.18.1          py311h06a4308_1
jinja2                    3.1.3           py311h06a4308_0
jpeg                      9e                   h5eee18b_1
json5                     0.9.6              pyhd3eb1b0_0
jsonschema                4.19.2          py311h06a4308_0
jsonschema-specifications 2023.7.1        py311h06a4308_0
jupyter                   1.0.0           py311h06a4308_8
jupyter-lsp               2.2.0           py311h06a4308_0
jupyter_client            8.6.0           py311h06a4308_0
jupyter_console           6.6.3           py311h06a4308_0
jupyter_core              5.5.0           py311h06a4308_0
jupyter_events            0.8.0           py311h06a4308_0
jupyter_server            2.10.0          py311h06a4308_0
jupyter_server_terminals  0.4.4           py311h06a4308_1
jupyterlab                4.0.11          py311h06a4308_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.25.1          py311h06a4308_0
jupyterlab_widgets        3.0.9           py311h06a4308_0
krb5                      1.20.1               h143b758_1
lapack                    3.9.0                    netlib    conda-forge
latexcodec                2.0.1                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1
libblas                   3.9.0           1_h86c2bf4_netlib    conda-forge
libclang                  14.0.6          default_hc6dbbc7_1
libclang13                14.0.6          default_he11475f_1
libcups                   2.4.2                h2d74bed_1
libcurl                   8.5.0                h251f7ec_0
libedit                   3.1.20230828         h5eee18b_0
libev                     4.33                 h7f8727e_1
libffi                    3.4.4                h6a678d5_0
libgcc-ng                 11.2.0               h1234567_1
libgfortran-ng            11.2.0               h00389a5_1
libgfortran5              11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
liblapack                 3.9.0           5_h92ddd45_netlib    conda-forge
libllvm14                 14.0.6               hdb19cb5_3
libnghttp2                1.57.0               h2d74bed_0
libpng                    1.6.39               h5eee18b_0
libpq                     12.17                hdbd6064_0
libsodium                 1.0.18               h7b6447c_0
libssh2                   1.10.0               hdbd6064_2
libstdcxx-ng              11.2.0               h1234567_1
libuuid                   1.41.5               h5eee18b_0
libxcb                    1.15                 h7f8727e_0
libxkbcommon              1.0.1                h5eee18b_1
libxml2                   2.10.4               hf1b16e4_1
lz4-c                     1.9.4                h6a678d5_0
lzo                       2.10                 h7b6447c_2
markupsafe                2.1.3           py311h5eee18b_0
matplotlib-inline         0.1.6           py311h06a4308_0
mistune                   2.0.4           py311h06a4308_0
mkl                       2023.1.0         h213fc3f_46344
mkl-service               2.4.0           py311h5eee18b_1
mkl_fft                   1.3.8           py311h5eee18b_0
mkl_random                1.2.4           py311hdb19cb5_0
mysql                     5.7.24               h721c034_2
nbclient                  0.8.0           py311h06a4308_0
nbconvert                 7.10.0          py311h06a4308_0
nbformat                  5.9.2           py311h06a4308_0
ncurses                   6.4                  h6a678d5_0
nest-asyncio              1.5.6           py311h06a4308_0
notebook                  7.0.6           py311h06a4308_0
notebook-shim             0.2.3           py311h06a4308_0
numexpr                   2.8.7           py311h65dcdc2_0
numpy                     1.26.3          py311h08b1b3b_0
numpy-base                1.26.3          py311hf175353_0
numpydoc                  1.5.0           py311h06a4308_0
openssl                   3.0.13               h7f8727e_0
overrides                 7.4.0           py311h06a4308_0
packaging                 23.1            py311h06a4308_0
pandocfilters             1.5.0              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
pcre                      8.45                 h295c915_0
pexpect                   4.8.0              pyhd3eb1b0_3
pip                       23.3.1          py311h06a4308_0
platformdirs              3.10.0          py311h06a4308_0
ply                       3.11            py311h06a4308_0
prettytable               3.5.0           py311h06a4308_0
prometheus_client         0.14.1          py311h06a4308_0
prompt-toolkit            3.0.43          py311h06a4308_0
prompt_toolkit            3.0.43               hd3eb1b0_0
psutil                    5.9.0           py311h5eee18b_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pure_eval                 0.2.2              pyhd3eb1b0_0
py-cpuinfo                9.0.0           py311h06a4308_0
pybtex                    0.24.0                   pypi_0    pypi
pybtex-docutils           1.0.3                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.15.1          py311h06a4308_1
pyqt                      5.15.10         py311h6a678d5_0
pyqt5-sip                 12.13.0         py311h5eee18b_0
pytables                  3.9.2           py311h9d13977_0
python                    3.11.7               h955ad1f_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2          py311h06a4308_0
python-json-logger        2.0.7           py311h06a4308_0
pytz                      2023.3.post1    py311h06a4308_0
pyyaml                    6.0.1           py311h5eee18b_0
pyzmq                     25.1.2          py311h6a678d5_0
qt-main                   5.15.2              h53bd1ea_10
qtconsole                 5.5.0           py311h06a4308_0
qtpy                      2.4.1           py311h06a4308_0
readline                  8.2                  h5eee18b_0
referencing               0.30.2          py311h06a4308_0
requests                  2.31.0          py311h06a4308_1
rfc3339-validator         0.1.4           py311h06a4308_0
rfc3986-validator         0.1.1           py311h06a4308_0
rpds-py                   0.10.6          py311hb02cf49_0
scipy                     1.11.4          py311h08b1b3b_0
send2trash                1.8.2           py311h06a4308_0
setuptools                68.2.2          py311h06a4308_0
sip                       6.7.12          py311h6a678d5_0
six                       1.16.0             pyhd3eb1b0_1
sniffio                   1.3.0           py311h06a4308_0
snowballstemmer           2.2.0              pyhd3eb1b0_0
soupsieve                 2.5             py311h06a4308_0
sphinx                    5.0.2           py311h06a4308_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-bibtex      2.6.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
sqlite                    3.41.2               h5eee18b_0
stack_data                0.2.0              pyhd3eb1b0_0
tbb                       2021.8.0             hdb19cb5_0
terminado                 0.17.1          py311h06a4308_0
tinycss2                  1.2.1           py311h06a4308_0
tk                        8.6.12               h1ccaba5_0
tornado                   6.3.3           py311h5eee18b_0
traitlets                 5.7.1           py311h06a4308_0
typing-extensions         4.9.0           py311h06a4308_1
typing_extensions         4.9.0           py311h06a4308_1
tzdata                    2023d                h04d1e81_0
urllib3                   2.1.0           py311h06a4308_0
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1           py311h06a4308_1
websocket-client          0.58.0          py311h06a4308_4
wheel                     0.41.2          py311h06a4308_0
widgetsnbextension        4.0.5           py311h06a4308_0
xz                        5.4.5                h5eee18b_0
yaml                      0.2.5                h7b6447c_0
zeromq                    4.3.5                h6a678d5_0
zlib                      1.2.13               h5eee18b_0
zlib-ng                   2.0.7                h5eee18b_0
zstd                      1.5.5                hc292b87_0 

**Additional Context**<br/>

**Comment by gonuke** [comment]
Thanks for your message.  I think this is because we haven't managed to update for Cython 3 yet.  Please try with "cython<3" in your condo install.

**Comment by tom-neville** [comment]
Hi Paul,

Thanks very much for your prompt response. That fixed the problem.

Cheers,
Tom Neville

**Comment by ahnaf-tahmid-chowdhury** [comment]
Yesterday, I was trying with Cython3 and received the following error while compiling the enrichment:

```
[ 64%] Compiling Cython CXX source for enrichment...

Error compiling Cython file:
------------------------------------------------------------
...
            return self._mat_feed
    
        def __set__(self, value):
            cdef pyne.material._Material value_proxy
            value_proxy = pyne.material.Material(value, free_mat=not isinstance(value, pyne.material._Material))
            (<cpp_enrichment.Cascade *> self._inst).mat_feed = value_proxy.mat_pointer[0]
                                                                                      ^
------------------------------------------------------------

/mnt/Data/Projects/PyNE/pyne/enrichment.pyx:183:86: Cannot assign type 'Material &' to 'Material'

Error compiling Cython file:
------------------------------------------------------------
...
            return self._mat_prod
    
        def __set__(self, value):
            cdef pyne.material._Material value_proxy
            value_proxy = pyne.material.Material(value, free_mat=not isinstance(value, pyne.material._Material))
            (<cpp_enrichment.Cascade *> self._inst).mat_prod = value_proxy.mat_pointer[0]
                                                                                      ^
------------------------------------------------------------

/mnt/Data/Projects/PyNE/pyne/enrichment.pyx:200:86: Cannot assign type 'Material &' to 'Material'

Error compiling Cython file:
------------------------------------------------------------
...
            return self._mat_tail
    
        def __set__(self, value):
            cdef pyne.material._Material value_proxy
            value_proxy = pyne.material.Material(value, free_mat=not isinstance(value, pyne.material._Material))
            (<cpp_enrichment.Cascade *> self._inst).mat_tail = value_proxy.mat_pointer[0]
                                                                                      ^
------------------------------------------------------------

/mnt/Data/Projects/PyNE/pyne/enrichment.pyx:217:86: Cannot assign type 'Material &' to 'Material'
```
This typically happens when there's a mismatch in types or when Cython is unable to infer the correct type.

So, in the `__set__` method, I’ve replaced `value_proxy.mat_pointer[0]` with `deref(value_proxy.mat_pointer)`. The `deref` function is used to dereference the pointer and get the actual object. But, it seems, the issue still remains the same.

**Comment by gonuke** [comment]
Closing this in favor of #1522
