### ISSUE TITLE
Pyne not appearing in Conda Forge Channels

### ISSUE THREAD

**Issue by Teancum-Q** [pyne/pyne#1521]
**Describe the Bug**<br/>
Hi, I'm trying to install pyne via conda, and none of the conda forge channels are finding pyne as a package name. I tried other conda forge channels as well, with the same result. 

**Expected Behavior**<br/>
I expected conda to find the package. 

**Screenshots or Code Snippets**<br/>

(pyne) C:\Users\QUISTE>conda install -c conda-forge pyne
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pyne

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults

**Please complete the following information regarding your system:**<br/>
 - OS: Windows

**Additional Context**<br/>

**Comment by ahnaf-tahmid-chowdhury** [comment]
PyNE is not currently compatible with Windows. Instead, please consider using Linux via WSL or utilize VirtualBox.

**Comment by Teancum-Q** [comment]
Well that's disappointing. Thank you for your response though.

**Comment by Dcx0x** [comment]
Hi,
Do you know if there is any plan in the future for pyne to be compatible with Windows, @ahnaf-tahmid-chowdhury ?

**Comment by ahnaf-tahmid-chowdhury** [comment]
Yes @Dcx0x, we are redesigning PyNE's build method. Once it is complete, we may proceed to support Windows as well. However, please note that Windows may not support all the features that PyNE can provide. For now, if you are using Windows and want to run PyNE, you can use [NukeLab](https://nukehub.org/nuke-lab).

**Comment by Dcx0x** [comment]
Thanks for your answer!
I'll try and come check when the next version is realeased.
