### ISSUE TITLE
Fatal Error: 'pyne_version.h' file not found 

### ISSUE THREAD

**Issue by sudo-nano** [pyne/pyne#1530]
**Describe the Bug**<br/>
PyNE build fails during compilation of `endftod.f90.o` due to `utils.cpp` not being able to find `pyne_version.h`

```sh
/Users/cwg1231/Downloads/pyne/src/utils.cpp:14:10: fatal error: 'pyne_version.h' file not found
#include "pyne_version.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
```

**To Reproduce**<br/>
1. Clone repository 
2. Run `python3.11 setup.py install --user -j $(nproc) --slow`

**Expected Behavior**<br/>
PyNE builds and installs 

**Screenshots or Code Snippets**<br/>
```sh
/Users/cwg1231/Downloads/pyne/src/utils.cpp:14:10: fatal error: 'pyne_version.h' file not found
#include "pyne_version.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
```

**Please complete the following information regarding your system:**<br/>
 - OS: MacOS Sonoma 14.4
 - PyNE Version: 0.7.8
 - Versions of dependencies installed with: 
   - Fortran Compiler: gcc version 13.2.0 (Homebrew GCC 13.2.0)
   - C++ Compiler: Apple clang version 15.0.0 (clang-1500.3.9.4)
   - CMake: 3.29.2
   - NumPy 1.26.4
   - SciPy 1.13.0 
   - Cython 3.0.10
    - HDF5: 1.14.3
    - PyTables: 3.9.2
    - BLAS: openblas 0.3.27
    - Jinja2: 3.1.3

**Additional Context**<br/>
Building with `--slow` is required for me because I'm on Apple silicon (ARM).

**Comment by sturmk** [comment]
I'm having the same issue on Ubuntu 23.10, with x86_64 architecture.
Workaround: go to `$PYNE_SRC_DIR/build/pyne` and execute `python3 pyne_version.py`; then the build process can be resumed.

**Comment by gonuke** [comment]
I expect there is an error earlier in the build process that you are missing.  This file should be generated by running a python script during the build configuration.

This script is run by invoking `python` but on some systems this doesn't exist and only `python3` exists.

We'll have to find a more robust solution, but in the meantime, in addition to the workaround suggested by @sturmk, one can also ensure that the `python` command exists with either a symlink or `update-alternatives` on Ubuntu.
