### ISSUE TITLE
Fails to find moab-5.5.1

### ISSUE THREAD

**Issue by yurivict** [pyne/pyne#1537]
**Describe the Bug**<br/>
Since moab was updated 5.3.1 → 5.5.1 PyNE-0.7.8 fails to find moab, and as a consequence fails to build pyne/source_sampling.so

**Please complete the following information regarding your system:**<br/>
 - OS: FreeBSD 14.0
 - PyNE Version: 0.7.8

**Additional Context**<br/>
FreeBSD port build.

**Comment by gonuke** [comment]
Thanks for sharing this. We recently worked on a number of updates for PyNE including newer MOAB as well as newer HDF5 and Cython (#1529) and will hopefully have a new release soon.

**Comment by yurivict** [comment]
Removing cmake/FindMOAB.cmake fixed the problem.
MOAB provides its own cmake scripts, and you should use them instead of overriding them with a dysfunctional cmake/FindMOAB.cmake module, if this isn't yet done in #1529.

**Comment by yurivict** [comment]
@gonuke 
The latest develop branch revision [94655cf](https://github.com/pyne/pyne/commit/94655cfb02c6abc5112a922019a2d0f17c5707a4) still fails to find moab.

You need to remove FindMOAB.cmake and use the MOAB-provided cmake scripts.

**Comment by gonuke** [comment]
I see!  It looks like our tests appeared to be successful, but upon digging deeper, they are NOT. Thanks for alerting us to this. We'll also need to improve testing.  #1526 is already aiming to solve this issue, and hopefully we can move that forward.

**Comment by ahnaf-tahmid-chowdhury** [comment]
> Removing cmake/FindMOAB.cmake fixed the problem.

It seems interesting. I need to check if it also works on other platforms.

**Comment by yurivict** [comment]
> It seems interesting. I need to check if it also works on other platforms.

configure finds MOAB when cmake/FindMOAB.cmake is removed, but then configure fails because some non-standard variables are used that were set by cmake/FindMOAB.cmake before.

**Comment by ahnaf-tahmid-chowdhury** [comment]
Fixed by #1526
