### ISSUE TITLE
ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by gakabani** [pyne/pyne#1542]
I am using Python 3.12, and I am getting the following error during installation.

  File "/Users/gamalakabani/Codes/PyNE/pyne/setup.py", line 38, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

It seems that Python version 3.12  no longer supports "imp". It is deprecated.

Also, please update the conda installation environment for easy of installation and use.

**Comment by gonuke** [comment]
It seems we use this in 2 places that it's not needed at all (`setup.py` and `setup_sub.py`) and two places that should be simple to replace (`test_dagmc.py` and `test_source_sample.py`).  In both of the latter two cases, we are testing for the existence of a `pyne` module before we decide to skip a test.  There may be an easier way, such as this from `test_r2s.py`:

```
     try:
        from pyne import dagmc
    except ImportError:
        pytest.skip()
```
