### ISSUE TITLE
CI workflow for MacOS

### ISSUE THREAD

**Issue by bennibbelink** [pyne/pyne#1555]
**Is your feature request related to an enhancement? Please describe.**<br/>
I would like to see a GitHub Actions workflow that builds and tests Pyne on both intel and arm macOS.

**Additional Context**<br/>
Originally proposed in https://github.com/pyne/data/pull/27 to test arm64 versions of pyne data.

**Comment by bennibbelink** [comment]
I started working on this on https://github.com/bennibbelink/pyne/tree/arm64-data and have gotten pyne to build.  Two tests are failing though: `test_material.py::test_material_xrays` and `test_material.py::test_material_photons`.  I'm not sure what the issue is, @bquan0 have you seen these failures before?

**Comment by bquan0** [comment]
@bennibbelink I have seen test fails in `test_material.py` due to UnicodeDecodeError, but I haven't seen those specific tests fail.

**Comment by gonuke** [comment]
It looks like the failures are floating point comparisons along long lists of nuclides, where a single nuclide in the list violates the condition of "close" and has a relative difference between the two values of O(1e-16).

We may want to change `rtol` in line 51 of `test_material.py` to be 1e-15.  This is probably a reasonable discrepancy to allow as it's near machine precision.
