### ISSUE TITLE
Compare pytables hdf5 version to linked hdf5 version during build

### ISSUE THREAD

**Issue by crbates** [pyne/pyne#226]
A version mismatch between the hdf5 libraries pytables links against and the ones that pyne is linking against can cause hard to track down crashes. Adding a version comparison, if possible, would be desirable.

**Comment by scopatz** [comment]
not even sure if this is still an issue.

**Comment by crbates** [comment]
This is/was only an issue on windows where rogue dll's cause problems.

**Comment by gonuke** [comment]
Not reproducible, please open new issue if found again.
