### ISSUE TITLE
Implement MAGIC in mesh based variance reduction

### ISSUE THREAD

**Issue by elliottbiondo** [pyne/pyne#344]
The MAGIC [1] method is a simple way to generate mesh-based Monte Caro weight windows for global variance reduction, using an estimation of forward flux. Current capability lives [here](https://github.com/svalinn/r2s-act/blob/master/scripts/tools/magic.py), but has no business doing so. This should be added to the ```variance_reduction``` module. Using the ```Mesh```, ```Meshtally```, and ```Wwinp``` classes, this feature should be fairly straightforward. 

[1] A. DAVIS, “Comparison of global variance reduction techniques for Monte Carlo radiation transport simulations of ITER,” Fusion Engineering and Design, 86, 2698–2700 (2011).

**Comment by scopatz** [comment]
Closed by #589
