### ISSUE TITLE
nuc_data_make error on brand new fresh install

### ISSUE THREAD

**Issue by gidden** [pyne/pyne#354]
on a fresh ubuntu box, I get the following after first calling `python setup.py install --user`

```
14:45 ~/work/pyne [staging|…2]$ scripts/nuc_data_make 
Traceback (most recent call last):
  File "scripts/nuc_data_make", line 4, in <module>
    from pyne.dbgen.nuc_data_make import main
  File "/home/gidden/work/pyne/pyne/__init__.py", line 8, in <module>
    from .pyne_config import *
ImportError: No module named pyne_config
```

if I `cd` into scripts, it runs fine

**Comment by ghost** [comment]
Hi, 
I have just tried to install pyne on my Ubuntu 16.04 and I get a similar error, stating that the pyne.dbgen.nuc_data_make module is not found: 

Traceback (most recent call last):
  File "scripts/nuc_data_make", line 4, in <module>
    from pyne.dbgen.nuc_data_make import main
ImportError: No module named pyne.dbgen.nuc_data_make
Any ideas what is wrong? 
Thanks, 
Ash
