### ISSUE TITLE
Errors in example and tutorial ipython notebooks.

### ISSUE THREAD

**Issue by rachelslaybaugh** [pyne/pyne#576]
** The main problem seems to come from yt's PyneMoabHex8StaticOutput. This affects

(1) In the examples directory: 
- discretized_teapot.ipynb
- fng_model.ipynb
- mesh_tags.ipynb

(2) In the tutorial directory:
- 00-intro.ipynb
- 07-mesh-basics.ipynb
- 08-diffusion.ipynb

** There is an error in examples/origen22_h1_xs.ipynb because there is no BASE_TAPE9.INP file to parse. 

** There is an error in tutorial/05-cross-section.ipynb under the Cross Section Caching sections and I'm not sure what's wrong. It's claiming the init doesn't know the keyword 'data_source_classes', but the api indicates that it should.

**Comment by crbates** [comment]
I've opened #662 to close this

**Comment by scopatz** [comment]
closed by #622

**Comment by crbates** [comment]
#662 got moved to #667 this issue is still open pending yt fixes.

**Comment by scopatz** [comment]
Closed by #667
