### ISSUE TITLE
add amalgamation test to CI

### ISSUE THREAD

**Issue by crbates** [pyne/pyne#641]
This should run `amalgamate.py` and compile a simple c++ test program.

**Comment by crbates** [comment]
I'm moving this as pyne/pyne-amalgamation serves as a reasonable test for now.

**Comment by brewlius-cesar** [comment]
So, i'm pretty new to the GitHub scene.  Are you looking for anything more specific than:

> This should run amalgamate.py and compile a simple c++ test program.

**Comment by scopatz** [comment]
@brewlius-cesar, on Travis, we should download the https://github.com/pyne/pyne-amalgamation repo and run make.  This hasn't been implemented yet.  If you are interested in giving this a shot, you (just?) have to edit the `.travis.yml` file in the root pyne dir and then open a PR.

**Comment by scopatz** [comment]
Travis builds will be triggered any time you push a new commit to a PR.
