### ISSUE TITLE
Trouble getting dev working on Yosemite

### ISSUE THREAD

**Issue by wkerzendorf** [pyne/pyne#693]
I'm using anaconda and building works fine(using macports gfortran) with `FC=gfortran-mp-4.9 python setup.py install`
(see http://pastebin.com/R0urj4y4). `echo $LD_LIBRARY_PATH 
/Users/wkerzend/anaconda3/envs/nuclear/lib:/Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7`
and when I launch ipython and do `from pyne.material import Material` - I get:

```python
/Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/__init__.py:15: Warning: Error importing PyNE: you should not try to import PyNE from its source directory; please exit the PyNE source tree, and relaunch your python interpreter from there.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-19a8efb817bc> in <module>()
----> 1 from pyne.material import Material

/Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/__init__.py in <module>()
      8 
      9 try:
---> 10     from .pyne_config import *
     11 except ImportError:
     12     msg = ("Error importing PyNE: you should not try to import PyNE from "

ImportError: dlopen(/Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/pyne_config.so, 2): Library not loaded: libhdf5.9.dylib
  Referenced from: /Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/pyne_config.so
  Reason: image not found
```

**Comment by scopatz** [comment]
Hi Wolfgang,

It looks like you might be trying to run this from the pyne directory. Is
that true?  If so please move the notebook and your current location into
another directory and try again.

Be Well
Anthony

**Comment by wkerzendorf** [comment]
never mind - I'm being stupid on mac it is: DYLD_LIBRARY_PATH. Maybe the setup script can print that out (it's already very good!!! - that would be a minor improvement).

**Comment by wkerzendorf** [comment]
Well now it's falling over at 

```python
from pyne.material import Material
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-19a8efb817bc> in <module>()
----> 1 from pyne.material import Material

ImportError: dlopen(/Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/material.so, 2): Symbol not found: __ZN4Json5ValueixERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE
  Referenced from: /Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/material.so
  Expected in: /Users/wkerzend/anaconda3/envs/nuclear/lib/libpyne.dylib
 in /Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/material.so
```

**Comment by wkerzendorf** [comment]
@scopatz the decay thing you sent me seems to be new in 0.5 right?

**Comment by scopatz** [comment]
@wkerzendorf yes, decay is new in v0.5.  So you need to be on the develop or v0.5.0-release branch.

**Comment by scopatz** [comment]
Also, thanks for the point about the DYLD_...PATH.  We'll make that change.

**Comment by scopatz** [comment]
Also a v0.5 conda package will come out with the new release - hopefully very soon.

**Comment by wkerzendorf** [comment]
@scopatz so any idea about `Symbol not found: __ZN4Json5ValueixERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE` ?

**Comment by scopatz** [comment]
Hmm sorry, I didn't see that.

**Comment by scopatz** [comment]
What is the output of?

```bash
$ ldd /Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/material.so
```

**Comment by wkerzendorf** [comment]
It's a mac so here is otool:
```
otool -L /Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/material.so
/Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/material.so:
	libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
	@rpath/libpyne.dylib (compatibility version 0.0.0, current version 0.0.0)
	libhdf5.9.dylib (compatibility version 10.0.0, current version 10.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

```

**Comment by scopatz** [comment]
Hmmm It seems like `@rpath/libpyne.dylib` might need to be `@rpath/../lib/libpyne.dylib`.  I think @crbates recently updated this (though our CI serves still test correctly).  Try the following:

```bash
$ ln -s /Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/lib/libpyne.dylib /Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne
```

**Comment by wkerzendorf** [comment]
@scopatz 
We're getting there :wink: 

```python
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-1-19a8efb817bc> in <module>()
----> 1 from pyne.material import Material

/Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/__init__.pyc in <module>()
      8 
      9 try:
---> 10     from .pyne_config import *
     11 except ImportError:
     12     msg = ("Error importing PyNE: you should not try to import PyNE from "

/Users/wkerzend/pyne/pyne_config.pyx in init pyne.pyne_config (/Users/wkerzend/software/pyne/build/pyne/pyne_config.cxx:2012)()

UnicodeDecodeError: 'ascii' codec can't decode byte 0x88 in position 0: ordinal not in range(128)
```

**Comment by crbates** [comment]
>Hmmm It seems like `@rpath/libpyne.dylib` might need to be `@rpath/../lib/libpyne.dylib`.  I think @crbates recently updated this (though our CI serves still test correctly).  Try the following:

>```bash
$ ln -s /Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/lib/libpyne.dylib /Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne
```
hmm, not sure where this loader path issue is coming from.  The current cmake file supposedly sets it correctly https://github.com/pyne/pyne/blob/v0.5.0-release/CMakeLists.txt#L139

**Comment by crbates** [comment]
@wkerzendorf have you installed cython into the virtual environment? it looks like system cython is being used in your pastebin. I'm not 100% sure why this would cause a problem but it's worth a shot.

**Comment by wkerzendorf** [comment]
@crbates maybe this will solve it - yes I did not realize.

**Comment by wkerzendorf** [comment]
@crbates @scopatz `UnicodeDecodeError: 'ascii' codec can't decode byte 0x88 in position 0: ordinal not in range(128)` wasn't solved by cython afaict

**Comment by wkerzendorf** [comment]
here http://pastebin.com/DQ3XsJQ4

**Comment by scopatz** [comment]
> hmm, not sure where this loader path issue is coming from. The current cmake file supposedly sets it correctly https://github.com/pyne/pyne/blob/v0.5.0-release/CMakeLists.txt#L139

Well that is good.  I thought it looked right before.

**Comment by scopatz** [comment]
@wkerzendorf where is the unicode issue on that pastebin?

**Comment by crbates** [comment]
It looks like cmake isn't finding your macports `c++` compiler and instead is using clang. This may be another possible source of the problem.

**Comment by wkerzendorf** [comment]
```
from pyne.material import Material
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-1-19a8efb817bc> in <module>()
----> 1 from pyne.material import Material

/Users/wkerzend/anaconda3/envs/nuclear/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/__init__.pyc in <module>()
      8 
      9 try:
---> 10     from .pyne_config import *
     11 except ImportError:
     12     msg = ("Error importing PyNE: you should not try to import PyNE from "

/Users/wkerzend/projects/reflex/schoenbeck_trial/pyne/pyne_config.pyx in init pyne.pyne_config (/Users/wkerzend/software/pyne/build/pyne/pyne_config.cxx:1986)()

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 0: ordinal not in range(128)
```

**Comment by wkerzendorf** [comment]
so you want me to use gcc?

**Comment by wkerzendorf** [comment]
building with gcc now

**Comment by wkerzendorf** [comment]
it did not like that: http://pastebin.com/4BaNVkhK

**Comment by crbates** [comment]
have you tried cleaning your build directory ie. `rm -f build` before running `setup.py` again?

**Comment by wkerzendorf** [comment]
I did `git clean -dfx` that purged everything. Any idea, what could have gone wrong?

**Comment by crbates** [comment]
It could be a c++ library mismatch ie. your linker was trying to use `libc++.dylib` (clang's version of the c++ implementation) but your compiler was building things expecting to link to the `libstdc++.dylib` (gcc) abi.

**Comment by wkerzendorf** [comment]
I'm using macports, so I doubt it, but am not sure. Does either of you guys use a mac with 10.10?

**Comment by wkerzendorf** [comment]
how close is your conda build? Do you have one on a private binstar repo? (Thanks for your help!!)

**Comment by scopatz** [comment]
It should be coming out in the next day or two.

**Comment by wkerzendorf** [comment]
@scopatz should I wait for that, or should we try to continue debugging building from source?

**Comment by wkerzendorf** [comment]
@crbates How do i tell the code to use gcc as a linker. LD?

**Comment by scopatz** [comment]
@wkerzendorf Probably both :).  Despite how it might feel, this debugging is super useful for us.  Thanks for putting up with it!

**Comment by wkerzendorf** [comment]
@scopatz I have written many codes and lots of people helped me debug. No problem at all. Give me things to try. I'm not sure how to proceed.

**Comment by wkerzendorf** [comment]
I'm also happy to skype or something to get the debugging done quicker.

**Comment by crbates** [comment]
At this point it would be useful to have the full output from the build script with a clean repo when trying to use gcc. We have cmake report most of the libraries it links to so hopefully that will help point to the issue.

**Comment by wkerzendorf** [comment]
have a look at this http://pastebin.com/KCX3PVfP

**Comment by wkerzendorf** [comment]
@scopatz @crbates let me know if you need more information

**Comment by crbates** [comment]
@wkerzendorf have you tried setting your macports compiler symlinks use `port select`. I still think you're getting some `c++` library linking mismatch. see https://trac.macports.org/wiki/UsingTheRightCompiler

**Comment by wkerzendorf** [comment]
@crbates that did it. It still doesn't run - but I've also cleared the conda environment.

**Comment by wkerzendorf** [comment]
@crbates it worked! last step File not found: `nuc_data.h5`

**Comment by crbates** [comment]
after install you need to run `nuc_data_make` to download the raw data and create `nuc_data.h5`

**Comment by wkerzendorf** [comment]
I just did - that's really nice that this works. so in summary `port select gcc` is the magic trick. Doesn't seem to work with clang

**Comment by scopatz** [comment]
Super glad this is working!

**Comment by wkerzendorf** [comment]
@scopatz @crbates It's very nice. Hey I have a suggestion for you guys: `astropy` has a very nice units-package that might be useful for converting between different masses. astropy is also well maintained. anyways - I thought it might be of interest.

**Comment by scopatz** [comment]
@wkerzendorf probably worth suggesting on the mailing list :)

**Comment by wkerzendorf** [comment]
@scopatz Any ETA on the conda build?

**Comment by scopatz** [comment]
Hi Wolfgang,

It might be a couple of weeks, sadly. We ran into some serious CI issues
and are now in the process of figuring out what to do.  Sorry for the delay!

Be Well
Anthony

**Comment by wkerzendorf** [comment]
@scopatz I just wanted to see if there is any update on the conda build. I saw quite a bit of activity on the repo, well done!
