### ISSUE TITLE
Building PyNE error

### ISSUE THREAD

**Issue by makeclean** [pyne/pyne#710]
For some reason, now when issuing

       python setup.py install --user

PyNE is instead installed in `/usr/local/` rather than `$USER/.local`

**Comment by scopatz** [comment]
Try a clean build.

**Comment by scopatz** [comment]
ie `rm -r build`, like a boss.

**Comment by makeclean** [comment]
This was from a fresh install

**Comment by scopatz** [comment]
Are you root?

**Comment by makeclean** [comment]
Nope

**Comment by makeclean** [comment]
It looks like the `CMAKE_INSTALL_PREFIX` is being set incorrectly

**Comment by scopatz** [comment]
Can you post the full output, please?

**Comment by scopatz** [comment]
probably.

**Comment by makeclean** [comment]
davisa@davisa-M14xR2 /data/opt/pyne (develop)$ python setup.py install --user
/usr/bin/cmake
CMake command is
cmake .. -DHAVE_SETUPTOOLS=TRUE -DPYTHON_EXECUTABLE=/usr/bin/python
-- The Fortran compiler identification is GNU
-- The CXX compiler identification is GNU 4.8.2
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- CMAKE_Fortran_IMPLICIT_LINK_DIRECTORIES = /usr/lib/gcc/x86_64-linux-gnu/4.8;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib;/opt/intel/composer_xe_2013_sp1.1.106/compiler/lib/intel64;/opt/intel/composer_xe_2013_sp1.1.106/mkl/lib/intel64
-- CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES = gfortran;m;quadmath;m;c
-- Build type: Release
-- Found HDF5: debug;/data/opt/dagmc/hdf5/lib/libhdf5_hl.so;/data/opt/dagmc/hdf5/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libm.so;optimized;/data/opt/dagmc/hdf5/lib/libhdf5_hl.so;/data/opt/dagmc/hdf5/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libm.so  
-- HDF5_LIBRARY_DIRS = /data/opt/dagmc/hdf5/lib
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- PYTHON_EXECUTABLE: /usr/bin/python
-- Could NOT find MOAB (missing:  MOAB_LIBRARY MOAB_INCLUDE_DIR) 
-- MOAB Found: FALSE
-- Found Cython: /usr/bin/cython  
-- Cython Version: Cython version 0.20.1post0
-- Pyne platform defined as: __LINUX__
CMAKE_Fortran_COMPILER full path: /usr/bin/f95
Fortran compiler: f95
No optimized Fortran compiler flags are known, we just try -O2...

                                  /   \       
                          )      ((   ))     (                          
(@)                      /|\      ))_((     /|\                          
|-|                     / | \    (/\|/\)   / | \                      (@) 
| | -------------------/--|-voV---\`|'/--Vov-|--\---------------------|-|
|-|                         '^`   (o o)  '^`                          | |
| |                               `\Y/'                               |-|
|-|                                                                   | |
| |        /\             ___           __  __             /\         |-|
|-|       /^~\           / _ \_   _  /\ \ \/__\           /^~\        | |  
| |       /^~\          / /_)/ | | |/  \/ /_\             /^~\        |-|
|-|       /^~\         / ___/| |_| / /\  //__             /^~\        | | 
| |       ^||`         \/     \__, \_\ \/\__/             ^||`        |-|  
|-|        ||                |____/                        ||         | | 
| |       ====                                            ====        |-|
|-|                                                                   | |
| |                                                                   |-|
|-|___________________________________________________________________| |
(@)              l   /\ /         ( (       \ /\   l                `\|-|
                 l /   V           \ \       V   \ l                  (@)
                 l/                _) )_          \I                   
                                   `\ /'
                                     `  


-- CMake Install Prefix: /usr/local
-- RPATH: $ORIGIN/../lib
-- NUMPY_VERSION_STRING = 1.8.2
-- Found Numpy: 1.8.2  
-- Include paths for /data/opt/pyne/src: /data/opt/dagmc/hdf5/include;/usr/lib/python2.7/dist-packages/numpy/core/include;/data/opt/pyne/src
-- Include paths for /data/opt/pyne/pyne: /data/opt/dagmc/hdf5/include;/usr/lib/python2.7/dist-packages/numpy/core/include;/data/opt/pyne/src
-- Include paths for /data/opt/pyne/pyne/xs: /data/opt/dagmc/hdf5/include;/usr/lib/python2.7/dist-packages/numpy/core/include;/data/opt/pyne/src;/usr/include/python2.7
-- Include paths for /data/opt/pyne: /data/opt/dagmc/hdf5/include;/usr/lib/python2.7/dist-packages/numpy/core/include
-- Copying C/C++ header files.
-- Copying Cython header files.
-- Copying scripts.
-- Configuring done
`

**Comment by scopatz** [comment]
`-- CMake Install Prefix: /usr/local` this is normal.  Does it actually install to /usr/local though?  Most of the installation happens through setuptools or distutils, not cmake.

**Comment by makeclean** [comment]
For Julie it did not, for me it goes to `$USER/.local/lib/python2.7/site-packages/pyne-0.5.0_rc1-py2.7.egg/`

**Comment by scopatz** [comment]
OK - what you are seeing is correct, @makeclean.  Can you do a clean build on Julies machine and post the *full* output, please?

**Comment by makeclean** [comment]
Oh, I see, it turns out thats where it went for Julie as well in the end, I thought it was some mis-labeling of some string combination due to a failing CMAKE_INSTALL_PREFIX. It used to go to ...site-packages/pyne didn't it? Is this a Python3 thing?

**Comment by makeclean** [comment]
False alarm!

**Comment by scopatz** [comment]
Well, we switched to using setuptools, if it is installed on the system, so that changes the install path.  Also, annoyingly you have to run `nuc_data_make` each time you install.  @crbates and I have a plan for fixing that behaviour.
