### ISSUE TITLE
System Install Fails Test

### ISSUE THREAD

**Issue by everythingfunctional** [pyne/pyne#725]
If pyne is installed as a system administrator (i.e. sudo setup.py install), one of the test cases fails when executed as a user, presumably because it does not have access to some file. This may not be of particular importance, just thought I'd mention it.

**Comment by scopatz** [comment]
Hi @bprichar, could you post the full error, please?

**Comment by everythingfunctional** [comment]
Attached is the output from the command run as:
[brad-Yoga-13:~/pyne/tests (develop)] nosetests &> ~/pyne_test_fail.txt

Note that if it is run as:
sudo nosetests
then it passes

...........................................................................................................................................................Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
.Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
........................................................................E...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Requested faceting tolerance: 0
Using faceting tolerance: 0.0001
The implicit complement bounds 22 surfaces
The implicit complement's total surface area = 3444.32
Requested faceting tolerance: 0
Using faceting tolerance: 0.0001
.Requested faceting tolerance: 0
Using faceting tolerance: 0.0001
The implicit complement bounds 22 surfaces
The implicit complement's total surface area = 3444.32
Requested faceting tolerance: 0
Using faceting tolerance: 0.0001
...Requested faceting tolerance: 0
Using faceting tolerance: 0.0001
The implicit complement bounds 22 surfaces
The implicit complement's total surface area = 3444.32
/usr/local/lib/python2.7/dist-packages/pyne-0.5.0_rc1-py2.7.egg/pyne/partisn.py:198: UserWarning: Please supply a larger mesh. Number of fine mesh intervals is less than 7.
  warn("Please supply a larger mesh. Number of fine mesh intervals is less than 7.")
.Requested faceting tolerance: 0
Using faceting tolerance: 0.0001
The implicit complement bounds 22 surfaces
The implicit complement's total surface area = 3444.32
.Requested faceting tolerance: 0
Using faceting tolerance: 0.0001
The implicit complement bounds 22 surfaces
The implicit complement's total surface area = 3444.32
.Requested faceting tolerance: 0
Using faceting tolerance: 0.0001
The implicit complement bounds 22 surfaces
The implicit complement's total surface area = 3444.32
/usr/local/lib/python2.7/dist-packages/pyne-0.5.0_rc1-py2.7.egg/pyne/partisn.py:198: UserWarning: Please supply a larger mesh. Number of fine mesh intervals is less than 7.
  warn("Please supply a larger mesh. Number of fine mesh intervals is less than 7.")
...Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475
..Requested faceting tolerance: 0
Using faceting tolerance: 0.001
The implicit complement bounds 6 surfaces
The implicit complement's total surface area = 431.475

# ..........................................................................................................................................................................

## ERROR: test_data_checksums.test_internal_hashes

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(_self.arg)
  File "/home/brad/pyne/tests/test_data_checksums.py", line 38, in test_internal_hashes
    hashtools.set_internal_hashes(pyne.nuc_data)
  File "/usr/local/lib/python2.7/dist-packages/pyne-0.5.0_rc1-py2.7.egg/pyne/dbgen/hashtools.py", line 53, in set_internal_hashes
    set_hash(item, nuc_data)
  File "/usr/local/lib/python2.7/dist-packages/pyne-0.5.0_rc1-py2.7.egg/pyne/dbgen/hashtools.py", line 120, in set_hash
    with tables.openFile(nuc_data, mode='a') as f:
  File "/usr/lib/python2.7/dist-packages/tables/_past.py", line 35, in oldfunc
    return obj(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/tables/file.py", line 318, in open_file
    return File(filename, mode, title, root_uep, filters, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/tables/file.py", line 791, in **init**
    self._g_new(filename, mode, **params)
  File "hdf5extension.pyx", line 359, in tables.hdf5extension.File._g_new (tables/hdf5extension.c:3814)
  File "/usr/lib/python2.7/dist-packages/tables/utils.py", line 183, in check_file_access
    check_file_access(filename, 'r+')
  File "/usr/lib/python2.7/dist-packages/tables/utils.py", line 190, in check_file_access
    % (filename,))
IOError: file `/usr/local/lib/python2.7/dist-packages/pyne-0.5.0_rc1-py2.7.egg/pyne/nuc_data.h5` exists but it can not be written

---

Ran 3727 tests in 44.834s

FAILED (errors=1)
 Something went wrong converting:          0
 Something went wrong converting:          0
 Something went wrong converting:

**Comment by scopatz** [comment]
Ohhh This basically means that you cannot run tests without the permissions of the user that installed because one part of the tests requires write access.  You should be able to fix this via:

``` bash
$ sudo chmod go+w /usr/local/lib/python2.7/dist-packages/pyne-0.5.0_rc1-py2.7.egg/pyne/nuc_data.h5
```

However, it is generally recommended to not install things as root, unless you are going to be running as root.

**Comment by everythingfunctional** [comment]
That's what I figured. It may be important to consider in the case that you intend to install on a multi-user system, but maybe not if you assume the person installing it will be the one to run the tests.

**Comment by scopatz** [comment]
I agree that this is non-ideal. @bprichar a pull request would be very welcome.

**Comment by everythingfunctional** [comment]
If you could give me an idea which test(s) to start looking at I can look into fixing it, but I also need to read the developer guidelines before I do too much.

**Comment by scopatz** [comment]
@bprichar whichever tests fail :).  I really didn't expect this kind of error in the first place so I am sort of a loss at where to look.  This specific issue seems to come up from the pyne/dbgen/hashtools.py file.  So maybe you should start there.  

Also, thanks for reading the dev guide :). Probably the style guide is the most important.
