### ISSUE TITLE
Serpent.py: Depletion with Serpent 2

### ISSUE THREAD

**Issue by jessejohns** [pyne/pyne#744]
Serpent 2 has a different format for depletion studies than Serpent 1 (_dep.m file).  It includes block that looks like the following:

i922340 = 1; iU234             = 1;
i922350 = 2; iU235             = 2;
i922360 = 3; iU236             = 3;
...
i641560 = 73; iGd156            = 73;
i641570 = 74; iGd157            = 74;
i641600 = 75; iGd160            = 75;
iLOST    = 76;
iTOT     = 77;

This causes trouble with the parser.  Everything else is just fine.

This is true from version 2.1.12 to 2.1.24.

**Comment by scopatz** [comment]
Thanks for reporting!

**Comment by katyhuff** [comment]
@moatazharb @andrewryh why does this remain open ? Have the commits referenced above not quite fixed the issue? I know new issues may be arising (CC @ZoeRichter) with this depletion parser with newer versions of serpent but they seem to be different.  Any thoughts here?

**Comment by andrewryh** [comment]
> @moatazharb @andrewryh why does this remain open ? Have the commits referenced above not quite fixed the issue? I know new issues may be arising (CC @ZoeRichter) with this depletion parser with newer versions of serpent but they seem to be different. Any thoughts here?

I think I fixed it: https://github.com/pyne/pyne/pull/891
And this fix went to 0.6 release.

In fact, I having to problems with parsing _dep.m files from Serpent 2.1.29-31.

So, we can close this issue though.

**Comment by katyhuff** [comment]
Ok, sounds good.
