### ISSUE TITLE
Issue when reading ensdf decay file

### ISSUE THREAD

**Issue by snschune** [pyne/pyne#779]
Hi, first time using PyNE so this might be really obvious or I'm re-reporting a known issue. 
I'm using the PyNE virtual box http://pyne.io/install/vb.html#vb (0.5.0-rc1). I want to use the
`ensdf.decay()` function but I get an error when `decay()` tries to override a tuple entry:

>   File "/home/pyne-user/.local/lib/python2.7/site-packages/pyne/ensdf.py", line 1010, in decays
>     alpha[0] = parent
> TypeError: 'tuple' object does not support item assignment

This shouldn't happen because line 1010 can only be executed once since only one nuclide (U234)
decays to TH230 via alpha decay. The file is directly downloaded from nndc. 

My problem is illustrated here e6452b518ae12c7df7e75df2308cc3da66df7764

**Comment by scopatz** [comment]
Hi @snschune - it looks like you have also mad some other changes on the `issue_ensdf_decay` branch.  In the future please reference your branch and not the commit ID, so we don't have to go hunting for the relevant code. Thanks!

That said, I am looking into this now.

**Comment by snschune** [comment]
@scopatz  Thanks! I can't see the additional changes! All diffs w.r.t. the pyne/develop branch should be in the referenced ci. I'll link the branch in the future.

**Comment by scopatz** [comment]
Oh hah, the additional changes where from my develop branch not being up to date.

**Comment by snschune** [comment]
I'll check it and will give you a :+1:  if it works. I got this on my private computer
so it will be till tonight before I can test it. Thanks for the quick turnaround.

**Comment by scopatz** [comment]
No problem, @snschune

**Comment by snschune** [comment]
@scopatz looks like this fixes it - at least it runs through without erroring out. :+1:
Your patch fails tests in PR #780, though.

**Comment by snschune** [comment]
Working with the ensdf module a little bit, I find it relatively hard to navigate through the 
data it stores. Is there a rationale behind leaving it as a simple data type? 

I'd think that defining a decay class with clearly defined interfaces would be easier for the user. For example I realized that the gamma level entries moved from index 11 to 12 (or vice versa) in two different version I looked at. If you upgrade your PyNE you would need to modify your code as well.

**Comment by scopatz** [comment]
@snschune - I believe that this stuff is currently being overhauled to be more in line with your vision, but is not yet ready for public release.  @crbates is the primary author of the ENSDF stuff originally and may be able to tell you more.

**Comment by snschune** [comment]
Ok, sweet! I'll check the website for updates. Thanks!

**Comment by scopatz** [comment]
It is probably better to follow the pyne-users or pyne-develop mailing list.

**Comment by scopatz** [comment]
Are you doing that?

**Comment by snschune** [comment]
I do now! Thanks for your help.

**Comment by scopatz** [comment]
Probably should leave this open until the fix is merged
