### ISSUE TITLE
After merging #775, Installation fails with numpy 1.8.2

### ISSUE THREAD

**Issue by ohnemax** [pyne/pyne#783]
I just tried to install a freshly pulled instance, however it failed immediately with the arbitrary error `"ValueError: numpy version too low! 1.8.2 (have) < 1.8.0 (min)"`

(1.8.2. is Debian Jessie package)

It is unclear to me, if the failing is intented because 1.8.2 is not supported, or if it is just an issue that came up after #775.

**Comment by scopatz** [comment]
This is probably a post #755 issue.

**Comment by ohnemax** [comment]
I came up with a possible solution, please check.

**Comment by ohnemax** [comment]
Should be done with #784
