### ISSUE TITLE
Difficulty importing PyNE

### ISSUE THREAD

**Issue by kellyrowland** [pyne/pyne#787]
Hello,

I (seem to) have installed PyNE on 64-bit Scientific Linux 6.6, but am having difficulty importing it.

When I put the PyNE directory into my `PYTHONPATH`, I get the following import error:

```
  File "/global/home/users/krowland/warp/unionize.py", line 1, in <module>
    from pyne import ace
  File "/global/home/users/krowland/pyne-pyne-89d5f5d/pyne/__init__.py", line 15, in <module>
    raise ImportError(msg)
ImportError: Error importing PyNE: you should not try to import PyNE from
             its source directory; please exit the PyNE source tree, and relaunch
             your python interpreter from there.
```

However, if I exclude the PyNE directory from my `PYTHONPATH`, I instead fail because PyNE can't be found:

```
  File "/global/home/users/krowland/warp/unionize.py", line 1, in <module>
    from pyne import ace
ImportError: No module named pyne
```

My paths are as follows:

```
[krowland@n0012 ~/build-warp]$ echo $PATH
echo $PATH
/global/home/users/krowland/anaconda2/bin:/global/home/users/krowland/anaconda2/bin:/global/software/sl-6.x86_64/modules/langs/cuda/6.5/bin:/global/software/sl-6.x86_64/modules/tools/cmake/3.2.2/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/global/home/groups/allhands/bin:/global/home/users/krowland/bin:/global/home/groups/allhands/bin
[krowland@n0012 ~/build-warp]$ echo $LD_LIBRARY_PATH
echo $LD_LIBRARY_PATH
/global/software/sl-6.x86_64/modules/langs/cuda/6.5/lib64:/global/software/sl-6.x86_64/modules/langs/cuda/6.5/lib:/global/home/users/krowland/.local/lib/python2.7/site-packages/:/global/home/users/krowland/.local/lib/python2.7/site-packages/
[krowland@n0012 ~/build-warp]$ echo $PYTHONPATH
echo $PYTHONPATH
:/global/home/users/krowland/build-warp:/global/home/users/krowland/warp:/global/home/users/krowland/build-warp:/global/home/users/krowland/warp
```

Additionally, the commit at which I installed PyNE is 89d5f5d (from the tar [here](http://pyne.io/install/linux_source.html#linux-source)). I looked at issue #479 and put `/global/home/users/krowland/.local/lib/python2.7/site-packages/` in my `LD_LIBRARY_PATH` (as seen above, and because that's where PyNE was put on my system), but this has not helped the issue.

Any thoughts or suggestions would be hugely appreciated.

Thanks,
Kelly

**Comment by scopatz** [comment]
Hi @kellyrowland - when you installed pyne, what directory did it install to?  That is the dir that needs to be on the PYTHONPATH, not the source dir.  I would expect it to have a `site-packages` in the name somewhere and none of the dirs in you PYTHONPATH have that.  Also, what is the output of the following:

``` console
$ python -c 'import sys; print(sys.path); print(sys.__file__)'
```

**Comment by kellyrowland** [comment]
Hi @scopatz , thanks for the quick response. I think that PyNE was installed in the source directory:

```
[krowland@ln001 ~]$ ls pyne-pyne-89d5f5d/
CMakeLists.txt  configure.py   examples     pyne        tests
amalgamate.py   configure.pyc  execer.py    readme.rst  tutorial
build           cpp            img          scripts     xdressrc.py
cmake           docs           license.txt  setup.py
```

I know that out-of-source builds are generally preferred in computing; I was following the directions on the website since I'm on a cluster that's pretty new to me. Are there out-of-source install instructions anywhere? I know I've had this problem at least once in the past, but nothing relevant came up in my email history about this.

The output of that command is

```
[krowland@ln001 ~]$ python -c 'import sys; print(sys.path); print(sys.__file__)'
['', '/global/home/users/krowland/anaconda2/lib/python2.7/site-packages/Cython-0.23.4-py2.7-linux-x86_64.egg', '/global/home/users/krowland', '/global/home/users/krowland/build-warp', '/global/home/users/krowland/warp', '/global/home/users/krowland/anaconda2/lib/python27.zip', '/global/home/users/krowland/anaconda2/lib/python2.7', '/global/home/users/krowland/anaconda2/lib/python2.7/plat-linux2', '/global/home/users/krowland/anaconda2/lib/python2.7/lib-tk', '/global/home/users/krowland/anaconda2/lib/python2.7/lib-old', '/global/home/users/krowland/anaconda2/lib/python2.7/lib-dynload', '/global/home/users/krowland/.local/lib/python2.7/site-packages', '/global/home/users/krowland/anaconda2/lib/python2.7/site-packages', '/global/home/users/krowland/anaconda2/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg', '/global/home/users/krowland/anaconda2/lib/python2.7/site-packages/cryptography-1.0.2-py2.7-linux-x86_64.egg', '/global/home/users/krowland/anaconda2/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute '__file__'
```

**Comment by kellyrowland** [comment]
Update: I put `/global/home/users/krowland/.local/lib/python2.7/site-packages` into my `PYTHONPATH` and now get the error

```
Traceback (most recent call last):
  File "/global/home/users/krowland/warp/unionize.py", line 1, in <module>
    from pyne import ace
  File "__init__.pxd", line 155, in init pyne.ace (/global/home/users/krowland/pyne-pyne-89d5f5d/build/pyne/ace.cxx:29327)
ImportError: No module named numpy
```

Looks like we've found PyNE and have some different issues to sort out now. I'll close this issue since that resolved the missing PyNE problem. Thanks again!

**Comment by kellyrowland** [comment]
I'm reopening this issue because I'm having the same problem trying to import PyNE on the cluster referenced earlier in this issue. My `PYTHONPATH` is:

`
[krowland@ln000 /global/home/groups/co_nuclear/pyne/bin]$ echo $PYTHONPATH
/global/software/sl-6.x86_64/modules/python/2.7.8/cython/0.21/lib/python2.7/site-packages:/global/software/sl-6.x86_64/modules/python/2.7.8/scipy/0.14.0/lib/python2.7/site-packages:/global/software/sl-6.x86_64/modules/python/2.7.8/numpy/1.9.0/lib/python2.7/site-packages:/global/home/groups/co_nuclear/pyne/lib/python2.7/site-packages
`

I installed PyNE with the command

`
python setup.py install --prefix=/global/home/groups/co_nuclear/pyne
`

and get the following error when trying to import pyne:

`
[krowland@ln000 /global/home/groups/co_nuclear/pyne/bin]$ python
Python 2.7.8 (default, Oct 11 2014, 14:06:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
\>>> from pyne import ace
/global/home/groups/co_nuclear/pyne/lib/python2.7/site-packages/pyne/__init__.py:15: Warning: Error importing PyNE: you should not try to import PyNE from its source directory; please exit the PyNE source tree, and relaunch your python interpreter from there.
  warn(msg, Warning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/home/groups/co_nuclear/pyne/lib/python2.7/site-packages/pyne/__init__.py", line 10, in <module>
    from .pyne_config import *
ImportError: libpyne.so: cannot open shared object file: No such file or directory
`

(backslash escape char inserted above to make text appear as code and not as markdown triple quotes)

Any help or advice would be greatly appreciated!

**Comment by kellyrowland** [comment]
This was fixed inline with the following:

`
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/global/home/groups/co_nuclear/pyne/lib
export PYTHONPATH=$PYTHONPATH:/global/home/groups/co_nuclear/pyne/lib/python2.7/site-packages
`

The confusion stemmed from a problem related to #839 ; it is unclear from the installation messages that the "lib" directory should be added to the `LD_LIBRARY_PATH`.
