### ISSUE TITLE
Cooling time match in R2S is too rigid

### ISSUE THREAD

**Issue by gonuke** [pyne/pyne#799]
Users are invited to enter cooling times as floating point numbers with units.  The string formatting of these cooling times in the ALARA photon source output files is likely to be different from the string formatting used by the user to enter the times.  The R2S script relies (seems to rely) on string matching for these, rather than floating point comparison of some kind.

**Comment by elliottbiondo** [comment]
This is going to be more tricky than the other fixes due to the use of the functor in line 207 of `alara.py`:

``` python
matched_data = h5f.root.data.readWhere( "(nuc == '{0}') & (time == '{1}')".format(nuc, cond[1]))
```

**Comment by gonuke** [comment]
This may have been resolved by @zxkjack123

**Comment by mehmeturkmen** [comment]
> This may have been resolved by @zxkjack123

@gonuke @bam241 I check this issue out and it seems this issue have been solved by changing from string match to float match. 
Following lines, line 371 through 375 had been inserted to `alara.py`

`            # time match, convert string mathch to float mathch

            dt = _find_dt(cond[1], decay_times)

            # create of array of rows that match the nuclide/decay criteria

            matched_data = h5f.root.data.read_where("(nuc == '{0}') & (time == '{1}')".format(nuc, dt))       `

Please let me know if this is not the solution of this issue!

**Comment by gonuke** [comment]
Closed by PR in 2018
