### ISSUE TITLE
Pytables function names change

### ISSUE THREAD

**Issue by makeclean** [pyne/pyne#813]
Pytables have renamed many of their functions, http://www.pytables.org/MIGRATING_TO_3.x.html, which means that we fail to work with the newer version of PyTables. It looks like this can easily be remedied using their conversion script, however, if we want to maintain backwards compatability we need to do something like

```
   import tables as tb
   try:
       tb_version = tb.getPyTablesVersion()
  except:
       pass
  if tb_version == None:
      try: 
           tb_version = tb.get_pytables_version
      except import error:
           fail
```

With functions checking the version

```
  if tb_version == 2:
      with tb.openFile(mesh) as h5f:
  if tb_version > 2:
      with tb.open_file(mesh) as h5f:
```

But the number and style of changes makes my eyes bleed, perhaps someone more Pythonic than myself could take a look, or is this just the way it has to be?

**Comment by scopatz** [comment]
As the author of that conversion script (which incidentally was written with PyNE in mind), we should really just run it.  No one should be using PyTables 2.x  at this point, so we'd only be restricting ourselves to the v3.x series.

**Comment by gonuke** [comment]
This has been resolved.
