### ISSUE TITLE
global name 'iMesh' is not defined

### ISSUE THREAD

**Issue by jacoblandman** [pyne/pyne#821]
Hey guys, I'm a noob. I'm trying to run the first tutorial and I get this error:

File "/Users/jlandman/Library/Python/2.7/lib/python/site-packages/pyne/mesh.py", line 593, in **init**
    self.mesh = iMesh.Mesh()
NameError: global name 'iMesh' is not defined

I use macports, so most of my libraries are installed in /opt/local/
I installed moab.
I then installed pytaps via "pip install pytaps"

Hope you can help. Sorry if this is a repeat issue. I saw a different post that looked similar, but I didn't understand the responses. 
Here's what running cmake gives:

-- The C compiler identification is AppleClang 7.0.2.7000181
-- The CXX compiler identification is AppleClang 7.0.2.7000181
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found HDF5: debug;/opt/local/lib/libhdf5_hl.dylib;/opt/local/lib/libhdf5.dylib;/opt/local/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib;optimized;/opt/local/lib/libhdf5_hl.dylib;/opt/local/lib/libhdf5.dylib;/opt/local/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib  
-- HDF5_LIBRARY_DIRS = /opt/local/lib
-- Found PythonInterp: /opt/local/bin/python (found version "2.7.11") 
-- Found PythonLibs: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib
-- PYTHON_EXECUTABLE: /opt/local/bin/python
-- Found MOAB: /usr/local/lib/libMOAB.a  
-- MOAB header files: /usr/local/include
-- MOAB library: /usr/local/lib/libMOAB.a
-- MOAB Found: TRUE
-- Found Cython: /usr/local/bin/cython  
-- Cython Version: Cython version 0.23.1
-- Pyne platform defined as: **APPLE**

```
                              /   \       
                      )      ((   ))     (                          
```

(@)                      /|\      ))_((     /|\  
|-|                     / | \    (/|/)   / | \                      (@) 
| | -------------------/--|-voV---`|'/--Vov-|-----------------------|-|
|-|                         '^`(o o)  '^`                          | |
| |                               `\Y/'                               |-|
|-|                                                                   | |
| |        /\             ___           __  __             /\         |-|
|-|       /^~\           / _ _   _  /\ \ \/**\           /^~\        | |  
| |       /^~\          / /_)/ | | |/  \/ /_\             /^~\        |-|
|-|       /^~\         / ___/| |_| / /\  //**             /^~\        | | 
| |       ^||`\/     \__, \_\ \/\__/             ^||`        |-|  
|-|        ||                |____/                        ||         | | 
| |       ====                                            ====        |-|
|-|                                                                   | |
| |                                                                   |-|
|-|___________________________________________________________________| |
(@)              l   /\ /         ( (       \ /\   l                `\|-|
                 l /   V           \ \       V   \ l                  (@)
                 l/                _) )_          \I                   
`\ /'
                                     `  

-- CMake Install Prefix: /usr/local
-- RPATH: @loader_path/lib
-- NUMPY_VERSION_STRING = 1.10.4
-- Found Numpy: 1.10.4  
-- Include paths for /Users/jlandman/pyne/cpp: /opt/local/include;/usr/local/include;/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include;/Users/jlandman/pyne/cpp
-- Include paths for /Users/jlandman/pyne/pyne: /opt/local/include;/usr/local/include;/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include;/Users/jlandman/pyne/cpp
-- Include paths for /Users/jlandman/pyne/pyne/xs: /opt/local/include;/usr/local/include;/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include;/Users/jlandman/pyne/cpp;/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
-- Include paths for /Users/jlandman/pyne: /opt/local/include;/usr/local/include;/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include
-- Copying C/C++ header files.
-- Copying Cython header files.
-- Copying scripts.
-- Making Metadata.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jlandman/pyne

**Comment by scopatz** [comment]
@elliottbiondo  or @Pshriwise?

**Comment by elliottbiondo** [comment]
I am guessing there is some issue with your PyTAPS installation. For starters, could you try this in iPython:

```
>> from itaps import iMesh
```

**Comment by jacoblandman** [comment]
Yes I believe it was a PyTaps problem. I switched over to ubuntu and installed everything with no problems. Thanks!
