### ISSUE TITLE
CI Problems

### ISSUE THREAD

**Issue by makeclean** [pyne/pyne#827]
There are problems with PyNE CI right now regarding some weird GFORTRAN_1.4 bug. I have my suspicions but some digging will be required to fix it. @scopatz is in favour of switching to CircleCI, not knowing enough regarding the complexity of the switch, what this would buy us etc, I therefore am not educated enough to have an opinion. I will keep digging on this CI bug though.

**Comment by makeclean** [comment]
The issue is that during the Conda install process libgfortran is installed. 

```
The following NEW packages will be INSTALLED:
    cmake:       3.3.1-0           
    cython:      0.23.4-py27_0     
    hdf5:        1.8.15.1-2        
    lapack:      3.5.0-0           
    libgfortran: 3.0-0             
    mkl:         11.3.1-0          
```

Eventually libgfortran.so.3 is installed, but contains no symbols!

```
+ objdump -T /home/travis/miniconda/pkgs/libgfortran-3.0-0/lib/libgfortran.so.3
+ grep GFORTRAN_1.4
```

Installing gfortran on the test machine shows this from its specific libgfortran

```
+ objdump -T /home/travis/.local/lib/libgfortran.so.3
+ grep GFORTRAN_1.4
0000000000085520 g    DF .text  00000000000003ac  GFORTRAN_1.4 _gfortran_iall_i8
00000000000d5120 g    DF .text  0000000000000005  GFORTRAN_1.4 _gfortran_transfer_real_write
000000000008eb80 g    DF .text  000000000000033f  GFORTRAN_1.4 _gfortran_parity_l1
000000000008eec0 g    DF .text  00000000000003a5  GFORTRAN_1.4 _gfortran_parity_l2
```

So I guess the issue is due to the installation of libgfortran.so.3 from conda, which I think is either installed due to either lapack or scipy.

**Comment by scopatz** [comment]
Oh, this might come from the fact that we installed gfortran from the cyclus package.

**Comment by makeclean** [comment]
I'm thinking I'm going to try a pyne ci based on a Docker image containing all our dependencies and have that pulled at test time.

**Comment by scopatz** [comment]
Go for it!

**Comment by makeclean** [comment]
Ok so I have working Docker based CI solution for us, https://travis-ci.org/makeclean/pyne/jobs/116507210, however this only works for Python 2.7 right now. I think it should be fairly easy to get the other pythons working as well. What I have isn't the ultimate solution I think, I will take the Travis instructions and turn those into a shell script that is inserted into the Docker image, which will take the python version as an argument.

**Comment by scopatz** [comment]
Any working CI is better than broken or non-existent CI ;).  Can you please open a PR?

**Comment by makeclean** [comment]
Issues have now been addressed.
