### ISSUE TITLE
Missing ace module

### ISSUE THREAD

**Issue by wbinventor** [pyne/pyne#830]
I just installed the latest version of PyNe from the "develop" branch and tried to use the `pyne.ace` module as documented [here](http://pyne.io/pyapi/ace.html) but am unable to import the module:

``` ipython
In [1]: from pyne import ace
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8f846ca54419> in <module>()
----> 1 from pyne import ace

ImportError: cannot import name ace
```

I've used this module before from a prior installation on a different computer without any issues. Has anything changed recently which might preclude this module from installing properly? Or might I have missed a step in the installation procedure? Thanks for any help in advance.

**Comment by makeclean** [comment]
@wbinventor when I do that, I get this

```
>>> from pyne import ace
__main__:1: QAWarning: pyne.rxname is not yet QA compliant.
__main__:1: QAWarning: pyne.ace is not yet QA compliant.
>>> 
```

**Comment by wbinventor** [comment]
@makeclean that is what I observe on my (Ubuntu 14.04) machine with 48054559632adaec771a8fcb735b77f5b7254a43, but I see the error on my (Ubuntu 15.04) machine with 6b9005fc5fa86fa6482dd45a3b379486a198bf61.

In both cases I installed from source per the instructions as:

``` bash
python setup.py install --user
```

**Comment by gonuke** [comment]
This is probably resolved and/or deprecated.
