### ISSUE TITLE
Sometimes-incorrect installation message

### ISSUE THREAD

**Issue by kellyrowland** [pyne/pyne#839]
The PyNE installer assumes that the user installs the software with the `--user` option, giving incorrect directions if another option is used. Example:

I entered `python setup.py install --prefix=/global/home/groups/co_nuclear/pyne`.

When the installation was done, I was presented with:

`
NOTE: If you have not done so already, please be sure that your PATH and LD_LIBRARY_PATH (or DYLD_FALLBACK_LIBRARY_PATH on Mac OSX) has been appropriately set to the install prefix of pyne. For this install of pyne you may add the following lines to your '~/.bashrc' file or equivalent:
`

`
\# PyNE Environment Settings
export PATH="/global/home/users/krowland/pyne-0.5.0/bin:${PATH}"
export LD_LIBRARY_PATH="/global/home/users/krowland/pyne-0.5.0/${HOME}:${LD_LIBRARY_PATH}"
`

(escape character inserted to circumvent markdown formatting)

These additions to my paths wouldn't be of much use here considering the alternative installation directory. Maybe there would be a way to pull the user install directory from the setup command and insert that directory into the environment settings directive?

**Comment by scopatz** [comment]
Thanks for reporting this @kellyrowland.  This seems like something that is very fixable, but inspecting if the `--prefix` is passed in, and then passed down to the build system.

**Comment by scopatz** [comment]
Or rather the error message at the end.

**Comment by scopatz** [comment]
Mind taking a stab at it in a PR, please?

**Comment by kellyrowland** [comment]
Finally got around to looking into this and it looks like it was fixed somewhere along the way.
