### ISSUE TITLE
Truncation of mass weights when generating materials from plaintext

### ISSUE THREAD

**Issue by ghost** [pyne/pyne#844]
Hey folks,

I've only just come across PyNE – what a fantastic thing! Thank you for all your hard work. I have a question about reading in material compositions. When I supply a dictionary, I can create a new Material instance easily enough. However, when I try to read the same data from a plain text file called _concrete_composition_: 

> H 0.56
> O 49.75
> Na 1.71
> Mg 0.26
> Al 4.69
> Si 31.47
> S 0.13
> K 1.92
> Ca 8.28
> Fe 1.24

With the following code: 

```
from pyne.material import Material

concrete_from_file = Material()
concrete_from_file.from_text('concrete_composition')
print(concrete_from_file)
```

It only partially reads in the data, returning this:

> Material:
> mass = 0.0
> density = -1.0
> atoms per molecule = -1.0
> Al =  4.6
> Ca =  8.2
> Fe =  1.
> H =  0.5
> K =  1.9
> Mg =  0.2
> Na =  1.7
> O =  49.7
> S =  0.1
> Si =  31.4

Which has truncated some of the values. How do I stop this from happening? I don't know if this is relevant, but when I run the `expand_elements()` method on the concrete partially read from file, it doesn't work. It does work for the case read in from a dictionary.

**Comment by scopatz** [comment]
Hi @sprogg77 - thanks for reporting.  I am not sure that this is actually truncated, but might simply be the string representation.  What happens when you `print(mat.comp)` rather than just printing the material?  or how about the repr string, `print(repr(mat))`

**Comment by ghost** [comment]
So with `print(mat.comp)` I get an empty dictionary:

`{}`

Whereas `print(repr(mat))` gives:

`pyne.material.Material({}, 0.0, -1.0, -1.0, {"Al":" 4.6","Ca":" 8.2","Fe":" 1.","H":" 0.5","K":" 1.9","Mg":" 0.2","Na":" 1.7","O":" 49.7","S":" 0.1","Si":" 31.4"})`

For the Material generated from a dictionary I get the following for `print(mat.comp)`:

`{10000000: 0.005599440055994402, 80000000: 0.49745025497450257, 110000000: 0.017098290170982904, 120000000: 0.0025997400259974005, 130000000: 0.046895310468953115, 140000000: 0.31466853314668536, 160000000: 0.0012998700129987003, 190000000: 0.019198080191980802, 200000000: 0.0827917208279172, 260000000: 0.012398760123987601}`

And the following for `print(repr(mat))`:

`pyne.material.Material({10000000: 0.005599440055994402, 80000000: 0.49745025497450257, 110000000: 0.017098290170982904, 120000000: 0.0025997400259974005, 130000000: 0.046895310468953115, 140000000: 0.31466853314668536, 160000000: 0.0012998700129987003, 190000000: 0.019198080191980802, 200000000: 0.0827917208279172, 260000000: 0.012398760123987601}, 100.01, -1.0, -1.0, {})`

**Comment by scopatz** [comment]
This was a bona fide bug.  I have put in a fix in #845

**Comment by scopatz** [comment]
Also thanks for using pyne :)

**Comment by ghost** [comment]
Super! It's working now. Thank you very much.

**Comment by ghost** [comment]
Can I ask, what testing has the materials module undergone? I see the following message: `QAWarning: pyne.material is not yet QA compliant.` Should I be checking materials mixes by hand?

**Comment by scopatz** [comment]
Hi @sprogg77 - great! Glad that works for you.  Hopefully someone will merge it in soon.

**Comment by scopatz** [comment]
As per testing.  The Materials module is one of the most tested parts of pyne.  I think the QA warning is bad and is hurting us here and would be in favor of its removal.  @elliottbiondo, how do you feel about that?  What do you think needs to be done to make this up to spec?

**Comment by elliottbiondo** [comment]
@scopatz I agree with you 100% that the QA warnings are hurting us. The QA criteria are purposefully quite stringent so I don't know off the top of my head what would need to be done. Probably pyne.data would need to be QA'd first as it is a dependency. I think a better solution is to white list modules that are QA compliant rather then black list modules via import guards.
