### ISSUE TITLE
Error installing PyNE on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by moatazharb** [pyne/pyne#870]
I'm trying to install PyNE from a github repo clone (develop branch) by running the following command:
python setup.py -DMOAB_INCLUDE_DIR=path/to/MOAB/include  -DMOAB_LIBRARY=/path/to/MOAB/libMOAB.so install --user 
# and I got the following error:

[  1%] Building Fortran object src/CMakeFiles/alphad.dir/ensdf_processing/ALPHAD/alphad.f.o
f95: error: _LARGEFILE_SOURCE: No such file or directory
f95: error: _LARGEFILE64_SOURCE: No such file or directory
f95: error: _BSD_SOURCE: No such file or directory
src/CMakeFiles/alphad.dir/build.make:62: recipe for target 'src/CMakeFiles/alphad.dir/ensdf_processing/ALPHAD/alphad.f.o' failed
make[2]: **\* [src/CMakeFiles/alphad.dir/ensdf_processing/ALPHAD/alphad.f.o] Error 1
CMakeFiles/Makefile2:142: recipe for target 'src/CMakeFiles/alphad.dir/all' failed
make[1]: **\* [src/CMakeFiles/alphad.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
# make: **\* [all] Error 2

Note:
[1] I followed the same install procedure on Debian on another machine and got PyNE to install correctly.
[2] I installed PyNE few months ago on Ubuntu 16.04 LTS without MOAB and got it to install correctly
thanks

**Comment by epassaro** [comment]
I couldn't reproduce this issue on a fresh Ubuntu 16.04 LTS environment by making a build in a GitHub Actions pipeline, but this warning is thrown when compiling the same file:

```
Scanning dependencies of target alphad
[  0%] Building Fortran object src/CMakeFiles/alphad.dir/ensdf_processing/ALPHAD/alphad.f.o
[  1%] Building Fortran object src/CMakeFiles/alphad.dir/ensdf_processing/nsdflib95.f.o
[  2%] Linking Fortran executable alphad
gfortran: warning: CMakeFiles/alphad.dir/ensdf_processing/ALPHAD/alphad.f.o: linker input file unused because linking not done
gfortran: warning: CMakeFiles/alphad.dir/ensdf_processing/nsdflib95.f.o: linker input file unused because linking not done
[  2%] Built target alphad
```


See the configuration file and results [here](https://github.com/epassaro/pyne/actions/runs/204423984/workflow).

**Comment by gonuke** [comment]
This error is not reproducible, but there are lingering fortran issues captured in #1259
