### ISSUE TITLE
compilation on MACOSX 10.11 with gfortran 6.1

### ISSUE THREAD

**Issue by bam241** [pyne/pyne#871]
I have try it on the last develop commit  `#6e185e3`
I run `python setup.py install --user`
the installation fails:

> [  1%] Building Fortran object src/CMakeFiles/gtol.dir/ensdf_processing/GTOL/gtol.f.o
> /var/folders/0j/33fkd30s1qz90vt8l_fjdw9m0000gn/T//cczrm78N.s:4321:suffix or operands invalid for `move'
> /var/folders/0j/33fkd30s1qz90vt8l_fjdw9m0000gn/T//cczrm78N.s:4322:suffix or operands invalid for`move'
> /var/folders/0j/33fkd30s1qz90vt8l_fjdw9m0000gn/T//cczrm78N.s:4340:suffix or operands invalid for `move'
> /var/folders/0j/33fkd30s1qz90vt8l_fjdw9m0000gn/T//cczrm78N.s:4341:suffix or operands invalid for`move'
> /var/folders/0j/33fkd30s1qz90vt8l_fjdw9m0000gn/T//cczrm78N.s:4961:suffix or operands invalid for `move'
> /var/folders/0j/33fkd30s1qz90vt8l_fjdw9m0000gn/T//cczrm78N.s:4962:suffix or operands invalid for`move'
> 
> ...
> 
> /var/folders/0j/33fkd30s1qz90vt8l_fjdw9m0000gn/T//cczrm78N.s:19461:suffix or operands invalid for `move'
> /var/folders/0j/33fkd30s1qz90vt8l_fjdw9m0000gn/T//cczrm78N.s:19478:suffix or operands invalid for`move'
> /var/folders/0j/33fkd30s1qz90vt8l_fjdw9m0000gn/T//cczrm78N.s:19480:suffix or operands invalid for `move'
> /var/folders/0j/33fkd30s1qz90vt8l_fjdw9m0000gn/T//cczrm78N.s:19481:suffix or operands invalid for`move'
> make[2]: **\* [src/CMakeFiles/gtol.dir/ensdf_processing/GTOL/gtol.f.o] Error 1
> make[1]: **\* [src/CMakeFiles/gtol.dir/all] Error 2

It is fixed using gfortran 5.2 which is the version suggested for MacOS 10.10 (MacOSx 10.11 is supposed to use fortran 6.1 according to [gcc.gnu.org](https://gcc.gnu.org/wiki/GFortranBinaries#MacOS))

I am not sure if the issues comes from  gfortran 6.1 or from my setup...

**Comment by gonuke** [comment]
This is outdated and will not fix at this time.
