### ISSUE TITLE
Question about format string in pyne/fortranformat/_parser.py

### ISSUE THREAD

**Issue by apthorpe** [pyne/pyne#894]
Near the end of `parse_tokens()`, if the edit descriptor isn't matched an exception is thrown with:

```
            raise InvalidFormat('Could not identify edit descriptor '
                                'in sequence $s' % str(token_set))

```
Is `$s` a legitimate format string for `%`? It looks like a typo but I've been wrong before.

I'd prefer to refactor this to 

```
            raise InvalidFormat('Could not identify edit descriptor '
                                'in sequence {0:s}'.format(str(token_set)))

```
but I want to make sure I understand the code's intent before making that change.

**Comment by opotowsky** [comment]
Since the rest of the file uses `%s` I will change it to that

(Nevermind, using `string.format()` throughout!)

**Comment by opotowsky** [comment]
Closing, PR #1275 addresses this
