### ISSUE TITLE
PackageNotFoundError: Package missing in current linux-64 channels: 

### ISSUE THREAD

**Issue by terryphi** [pyne/pyne#897]
Hello,

From what I gather, the lastest version is 0.5.3.  Is this correct?

Based on this assumption, I entered.

" conda install -c cyclus -c pyne pyne=0.5.3"

Yet got

PackageNotFoundError: Package missing in current linux-64 channels: 
  - pyne 0.5.3*

Any ideas?  How do I find out what the latest version is?

**Comment by skc222** [comment]
Yes, the latest release is 0.5.3
But you need to use `conda install -c conda-forge pyne=0.5.3`  
https://github.com/pyne/pyne.github.com/pull/3 this PR fixes the above issue

**Comment by katyhuff** [comment]
@sck222 , can you please rebuild the pyne site and make a PR to master so that this change (which you have already made, clearly, in the pyne.github.io source) is reflected in the rendered HTML?

**Comment by skc222** [comment]
Done! @katyhuff
Link for my fork website- https://skc222.github.io/pyne.github.com/install/conda.html#conda . Let me know if there are any broken pages
Making PR for this
