### ISSUE TITLE
Add this paper to docs

### ISSUE THREAD

**Issue by scopatz** [pyne/pyne#910]
This cites PyNE http://www.sciencedirect.com/science/article/pii/S0306454917302906

**Comment by gonuke** [comment]
Maybe also see which of these might be added: 
https://scholar.google.com/scholar?hl=en&as_sdt=0%2C50&q=pyne+scopatz&btnG=

I also wonder if @epassaro has any publications from the TARDIS-SN group that reference PyNE?

**Comment by epassaro** [comment]
As far as I know the TARDIS [citation guidelines](https://tardis-sn.github.io/tardis/credits.html) mentions PyNE in Acknowledgments ([for example](https://www.aanda.org/articles/aa/full_html/2020/01/aa36137-19/aa36137-19.html)). But you should ask Wolfgang about this.

**Comment by gonuke** [comment]
closed by #1256
