### ISSUE TITLE
URL needed for test data in test_endf.py no longer accessible

### ISSUE THREAD

**Issue by kkiesling** [pyne/pyne#984]
As of this afternoon (if not earlier), the URLs for data used in the tests in `test_endf.py` below are no longer accessible. This causes the tests to fail with an error message.

`test_endf.test_u235`: http://t2.lanl.gov/nis/data/data/ENDFB-VII.1-neutron/U/235
`test_endf.test_discretize`: http://t2.lanl.gov/nis/data/data/ENDFB-VII.1-neutron/Ni/59
`test_endf.test_evaluation_neutron`: http://t2.lanl.gov/nis/data/data/ENDFB-VII.1-neutron/U/235
`test_endf.test_evaluation_decay`: http://t2.lanl.gov/nis/data/endf/decayVII.1/092_U_233
`test_endf.test_evaluation_electroatomic`: http://t2.lanl.gov/nis/data/data/ENDFB-VII-electroatomic/Mo/nat
`test_endf.test_evaluation_relaxation`: http://t2.lanl.gov/nis/data/endf/relaxation/Xe-relax

It is unclear to me if this is temporary or if the files/data have moved all together.

**Comment by scopatz** [comment]
Hi @kkiesling - I believe that ENDFB VIII is now out, so they probably got rid of the ENDFB VII files.  We should update.

**Comment by kkiesling** [comment]
Hmm, the urls do seem to work now so the issue may have just been temporary.

**Comment by scopatz** [comment]
Yeah I could not reproduce yesterday

**Comment by kkiesling** [comment]
A non issue then. Closing.
